FROM docker.io/cloudflare/sandbox:0.12.4

RUN git config --system init.defaultBranch main \
  && git config --system user.name "learnGit Student" \
  && git config --system user.email "student@learn-git.local"
