const lesson = ({
  id,
  title,
  titleMy,
  summary,
  summaryMy,
  command,
  commandLabel,
  commandLabelMy,
  tip,
  tipMy,
  challenge,
  readTime = "4 min",
  points,
  pointsMy,
  check,
  checkMy,
}) => ({
  id,
  title,
  eyebrow: "Step-by-step",
  readTime,
  summary,
  points,
  command,
  commandLabel,
  tip,
  challenge,
  check,
  my: {
    title: titleMy,
    eyebrow: "တစ်ဆင့်ချင်း လေ့လာမယ်",
    readTime: readTime.replace("min", "မိနစ်"),
    summary: summaryMy,
    points: pointsMy,
    commandLabel: commandLabelMy,
    tip: tipMy,
    check: checkMy,
  },
});

export const modules = [
  {
    id: "foundations",
    number: "01",
    title: "Git basics",
    description: "Know what Git saves. Set it up. Make your first repository.",
    duration: "18 min",
    difficulty: "Beginner",
    my: {
      title: "Git အခြေခံ",
      description: "Git က ဘာသိမ်းသလဲ သိမယ်။ Setup လုပ်မယ်။ ပထမ repository ဖန်တီးမယ်။",
      duration: "၁၈ မိနစ်",
      difficulty: "အစပြုသူ",
    },
    lessons: [
      lesson({
        id: "what-is-git",
        title: "What Git saves",
        titleMy: "Git က ဘာသိမ်းသလဲ",
        summary: "Git saves project snapshots. You can see changes, return to old work, and work safely.",
        summaryMy: "Git က project အခြေအနေကို မှတ်တမ်းတင်ပေးတယ်။ ပြောင်းလဲမှုကြည့်၊ အဟောင်းပြန်ယူ၊ စိတ်ချစွာ လုပ်နိုင်တယ်။",
        points: [
          { title: "Edit", copy: "Change files in your project." },
          { title: "Stage", copy: "Choose changes to save next." },
          { title: "Commit", copy: "Save one clear snapshot." },
        ],
        pointsMy: [
          { title: "ပြင်မယ်", copy: "Project file တွေကို ပြင်မယ်။" },
          { title: "ရွေးမယ်", copy: "သိမ်းမယ့် changes ကို ရွေးမယ်။" },
          { title: "သိမ်းမယ်", copy: "Commit တစ်ခုအဖြစ် သိမ်းမယ်။" },
        ],
        command: "git status",
        commandLabel: "Check your project",
        commandLabelMy: "Project အခြေအနေကြည့်ရန်",
        tip: "Run git status whenever you are unsure.",
        tipMy: "မသေချာတိုင်း git status ကို run ပါ။",
        challenge: "status",
        check: {
          question: "What does a commit save?",
          options: ["A project snapshot", "A GitHub password", "A new computer"],
          correct: 0,
          success: "Correct. A commit is a saved project snapshot.",
        },
        checkMy: {
          question: "Commit က ဘာကိုသိမ်းသလဲ။",
          options: ["Project snapshot", "GitHub password", "Computer အသစ်"],
          correct: 0,
          success: "မှန်ပါတယ်။ Commit က project snapshot တစ်ခုပါ။",
        },
      }),
      lesson({
        id: "setup-git",
        title: "Set your name and email",
        titleMy: "Name နဲ့ email ထည့်မယ်",
        summary: "Git adds your name and email to each commit. Set them once on your computer.",
        summaryMy: "Git က commit တိုင်းမှာ သင့် name နဲ့ email ထည့်တယ်။ Computer မှာ တစ်ကြိမ် setup လုပ်ရုံပါ။",
        points: [
          { title: "Name", copy: "Use the name your team knows." },
          { title: "Email", copy: "Use your GitHub email." },
          { title: "Check", copy: "List the saved settings." },
        ],
        pointsMy: [
          { title: "Name", copy: "Team က သိတဲ့ name ကိုသုံးပါ။" },
          { title: "Email", copy: "GitHub email ကိုသုံးပါ။" },
          { title: "စစ်မယ်", copy: "သိမ်းထားတဲ့ setting ကိုကြည့်ပါ။" },
        ],
        command: 'git config --global user.name "Your Name"',
        commandLabel: "Set your Git name",
        commandLabelMy: "Git name ထည့်ရန်",
        tip: "This name is public when you push commits to GitHub.",
        tipMy: "GitHub ကို push လုပ်ရင် ဒီ name ကို အများမြင်နိုင်တယ်။",
        challenge: "config",
        check: {
          question: "How often do you set the global name?",
          options: ["Usually once", "Before every commit", "Never"],
          correct: 0,
          success: "Right. Global settings normally need to be set once.",
        },
        checkMy: {
          question: "Global name ကို ဘယ်နှကြိမ် ထည့်ရမလဲ။",
          options: ["ပုံမှန် တစ်ကြိမ်", "Commit တိုင်းမတိုင်ခင်", "မထည့်ရ"],
          correct: 0,
          success: "မှန်ပါတယ်။ ပုံမှန် တစ်ကြိမ် setup လုပ်ရုံပါ။",
        },
      }),
      lesson({
        id: "first-repository",
        title: "Create a repository",
        titleMy: "Repository ဖန်တီးမယ်",
        summary: "Turn a normal project folder into a Git repository with one command.",
        summaryMy: "သာမန် project folder ကို command တစ်ခုနဲ့ Git repository ပြောင်းမယ်။",
        points: [
          { title: "Open", copy: "Open your project folder." },
          { title: "Initialize", copy: "Run git init once." },
          { title: "Confirm", copy: "Run git status." },
        ],
        pointsMy: [
          { title: "ဖွင့်မယ်", copy: "Project folder ကိုဖွင့်ပါ။" },
          { title: "စမယ်", copy: "git init တစ်ကြိမ် run ပါ။" },
          { title: "စစ်မယ်", copy: "git status run ပါ။" },
        ],
        command: "git init",
        commandLabel: "Start Git in this folder",
        commandLabelMy: "ဒီ folder မှာ Git စရန်",
        tip: "Do not run git init inside another Git repository.",
        tipMy: "Git repository တစ်ခုအတွင်းမှာ git init ထပ်မလုပ်ပါနဲ့။",
        challenge: "init",
        check: {
          question: "Which command starts a repository?",
          options: ["git init", "git start", "git new"],
          correct: 0,
          success: "Correct. git init starts Git in the current folder.",
        },
        checkMy: {
          question: "Repository စတဲ့ command က ဘာလဲ။",
          options: ["git init", "git start", "git new"],
          correct: 0,
          success: "မှန်ပါတယ်။ git init က လက်ရှိ folder မှာ Git စပေးတယ်။",
        },
      }),
    ],
  },
  {
    id: "daily-workflow",
    number: "02",
    title: "Save daily work",
    description: "Check changes. Stage the right files. Make clean commits.",
    duration: "22 min",
    difficulty: "Beginner",
    my: {
      title: "နေ့စဉ်အလုပ် သိမ်းမယ်",
      description: "Changes ကြည့်မယ်။ File ရွေးမယ်။ သန့်ရှင်းတဲ့ commit လုပ်မယ်။",
      duration: "၂၂ မိနစ်",
      difficulty: "အစပြုသူ",
    },
    lessons: [
      lesson({
        id: "check-changes",
        title: "Check changed files",
        titleMy: "ပြောင်းထားတဲ့ file ကြည့်မယ်",
        summary: "Check before you save. Git shows changed, new, and staged files.",
        summaryMy: "မသိမ်းခင် အရင်စစ်ပါ။ Git က ပြင်ထား၊ အသစ်ထည့်၊ ရွေးထားတဲ့ file တွေပြမယ်။",
        points: [
          { title: "Red", copy: "Changed but not staged." },
          { title: "Green", copy: "Ready for the next commit." },
          { title: "Clean", copy: "No unsaved changes." },
        ],
        pointsMy: [
          { title: "အနီ", copy: "ပြင်ထားပေမယ့် မရွေးရသေး။" },
          { title: "အစိမ်း", copy: "Commit လုပ်ဖို့ အဆင်သင့်။" },
          { title: "ရှင်းနေ", copy: "မသိမ်းရသေးတာ မရှိ။" },
        ],
        command: "git status",
        commandLabel: "See changed files",
        commandLabelMy: "ပြောင်းထားတဲ့ file ကြည့်ရန်",
        tip: "Read the status output from top to bottom.",
        tipMy: "Status output ကို အပေါ်ကနေ အောက်ထိဖတ်ပါ။",
        challenge: "status",
        check: {
          question: "When should you run git status?",
          options: ["Before and after changes", "Only once a year", "Only on GitHub"],
          correct: 0,
          success: "Correct. Check status often.",
        },
        checkMy: {
          question: "git status ကို ဘယ်အချိန် run သင့်လဲ။",
          options: ["အလုပ်မလုပ်ခင်နဲ့ လုပ်ပြီး", "တစ်နှစ်တစ်ကြိမ်", "GitHub မှာပဲ"],
          correct: 0,
          success: "မှန်ပါတယ်။ Status ကို မကြာခဏကြည့်ပါ။",
        },
      }),
      lesson({
        id: "stage-files",
        title: "Choose files to save",
        titleMy: "သိမ်းမယ့် file ရွေးမယ်",
        summary: "Staging lets you choose exactly what goes into the next commit.",
        summaryMy: "Staging က နောက် commit မှာ ပါမယ့် file ကို တိတိကျကျ ရွေးပေးတယ်။",
        points: [
          { title: "Review", copy: "Check the file list." },
          { title: "Add", copy: "Stage one file or all files." },
          { title: "Check", copy: "Run status again." },
        ],
        pointsMy: [
          { title: "ကြည့်မယ်", copy: "File list ကိုအရင်စစ်ပါ။" },
          { title: "ထည့်မယ်", copy: "File တစ်ခု သို့ အားလုံးရွေးပါ။" },
          { title: "ပြန်စစ်", copy: "Status ထပ်ကြည့်ပါ။" },
        ],
        command: "git add .",
        commandLabel: "Stage all current changes",
        commandLabelMy: "လက်ရှိ changes အားလုံးရွေးရန်",
        tip: "For clean commits, stage only files for one task.",
        tipMy: "Commit သန့်ဖို့ task တစ်ခုနဲ့ဆိုင်တဲ့ file ပဲရွေးပါ။",
        challenge: "add",
        check: {
          question: "What does staging do?",
          options: ["Selects the next changes", "Deletes the project", "Uploads to GitHub"],
          correct: 0,
          success: "Correct. Staging selects changes for the next commit.",
        },
        checkMy: {
          question: "Staging က ဘာလုပ်သလဲ။",
          options: ["နောက် changes ကိုရွေးတယ်", "Project ဖျက်တယ်", "GitHub တင်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ်။ နောက် commit ထဲက changes ကိုရွေးတာပါ။",
        },
      }),
      lesson({
        id: "make-commit",
        title: "Make a clear commit",
        titleMy: "ရှင်းလင်းတဲ့ commit လုပ်မယ်",
        summary: "A commit saves staged work. Use a short message that says what changed.",
        summaryMy: "Commit က ရွေးထားတဲ့အလုပ်ကို သိမ်းတယ်။ ဘာပြောင်းလဲဆိုတာ message တိုတိုရေးပါ။",
        points: [
          { title: "One task", copy: "Keep one idea per commit." },
          { title: "Short message", copy: "Start with an action word." },
          { title: "Confirm", copy: "Check the new commit." },
        ],
        pointsMy: [
          { title: "Task တစ်ခု", copy: "Commit တစ်ခုမှာ idea တစ်ခုပဲ။" },
          { title: "Message တိုတို", copy: "လုပ်ဆောင်ချက်နဲ့ စရေးပါ။" },
          { title: "စစ်မယ်", copy: "Commit အသစ်ကိုကြည့်ပါ။" },
        ],
        command: 'git commit -m "Add contributor guide"',
        commandLabel: "Save the staged changes",
        commandLabelMy: "ရွေးထားတဲ့ changes သိမ်းရန်",
        tip: "Good: Add search button. Avoid: update stuff.",
        tipMy: "ကောင်း: Add search button။ မကောင်း: update stuff။",
        challenge: "commit",
        check: {
          question: "Which message is clearer?",
          options: ["Add profile button", "changes", "work"],
          correct: 0,
          success: "Correct. Say exactly what the commit changes.",
        },
        checkMy: {
          question: "ဘယ် message က ပိုရှင်းလဲ။",
          options: ["Add profile button", "changes", "work"],
          correct: 0,
          success: "မှန်ပါတယ်။ ဘာပြောင်းလဲဆိုတာ တိတိကျကျရေးပါ။",
        },
      }),
    ],
  },
  {
    id: "branching",
    number: "03",
    title: "Use branches",
    description: "Create a safe work branch. Switch, merge, and handle conflicts.",
    duration: "25 min",
    difficulty: "Intermediate",
    my: {
      title: "Branch သုံးမယ်",
      description: "အလုပ်အတွက် branch ဖန်တီးမယ်။ ပြောင်းမယ်၊ merge လုပ်မယ်၊ conflict ဖြေရှင်းမယ်။",
      duration: "၂၅ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "create-branch",
        title: "Create a work branch",
        titleMy: "အလုပ် branch ဖန်တီးမယ်",
        summary: "Use a branch for each task. Your main branch stays stable.",
        summaryMy: "Task တစ်ခုစီအတွက် branch တစ်ခုသုံးပါ။ Main branch က တည်ငြိမ်နေမယ်။",
        points: [
          { title: "Update main", copy: "Start from current work." },
          { title: "Create", copy: "Use a clear branch name." },
          { title: "Work", copy: "Commit on the new branch." },
        ],
        pointsMy: [
          { title: "Main update", copy: "လက်ရှိအလုပ်ကနေ စပါ။" },
          { title: "ဖန်တီး", copy: "ရှင်းတဲ့ branch name သုံးပါ။" },
          { title: "လုပ်မယ်", copy: "Branch အသစ်မှာ commit လုပ်ပါ။" },
        ],
        command: "git switch -c feat/community-guide",
        commandLabel: "Create and switch branch",
        commandLabelMy: "Branch ဖန်တီးပြီး ပြောင်းရန်",
        tip: "Use names like feat/search or fix/menu.",
        tipMy: "feat/search သို့ fix/menu လို name သုံးပါ။",
        challenge: "branch",
        check: {
          question: "Why use a feature branch?",
          options: ["Keep main stable", "Make Git slower", "Delete history"],
          correct: 0,
          success: "Correct. A branch gives your task a safe place.",
        },
        checkMy: {
          question: "Feature branch ဘာကြောင့်သုံးလဲ။",
          options: ["Main ကိုတည်ငြိမ်စေဖို့", "Git နှေးစေဖို့", "History ဖျက်ဖို့"],
          correct: 0,
          success: "မှန်ပါတယ်။ Task အတွက် လုံခြုံတဲ့နေရာရတယ်။",
        },
      }),
      lesson({
        id: "switch-merge",
        title: "Switch and merge",
        titleMy: "Branch ပြောင်းပြီး merge လုပ်မယ်",
        summary: "Finish the task, return to main, then merge the branch.",
        summaryMy: "Task ပြီးရင် main ကိုပြန်၊ ပြီးတော့ branch ကို merge လုပ်ပါ။",
        points: [
          { title: "Commit", copy: "Save all task work." },
          { title: "Switch", copy: "Return to main." },
          { title: "Merge", copy: "Bring the branch into main." },
        ],
        pointsMy: [
          { title: "Commit", copy: "Task အလုပ်အားလုံး သိမ်းပါ။" },
          { title: "ပြောင်းမယ်", copy: "Main ကိုပြန်ပါ။" },
          { title: "ပေါင်းမယ်", copy: "Branch ကို main ထဲထည့်ပါ။" },
        ],
        command: "git merge feat/community-guide",
        commandLabel: "Merge the finished branch",
        commandLabelMy: "ပြီးသွားတဲ့ branch ကို merge ရန်",
        tip: "Run tests before and after merging.",
        tipMy: "Merge မလုပ်ခင်နဲ့ လုပ်ပြီး test run ပါ။",
        challenge: "merge",
        check: {
          question: "Where do you merge a finished feature?",
          options: ["Into main", "Into the recycle bin", "Into an email"],
          correct: 0,
          success: "Correct. Switch to main, then merge the feature.",
        },
        checkMy: {
          question: "ပြီးသွားတဲ့ feature ကို ဘယ်မှာ merge လုပ်လဲ။",
          options: ["Main ထဲ", "Recycle bin ထဲ", "Email ထဲ"],
          correct: 0,
          success: "မှန်ပါတယ်။ Main ကိုပြောင်းပြီး feature ကို merge လုပ်ပါ။",
        },
      }),
      lesson({
        id: "merge-conflicts",
        title: "Fix a merge conflict",
        titleMy: "Merge conflict ဖြေရှင်းမယ်",
        summary: "A conflict means Git needs your choice. Edit the file, stage it, and commit.",
        summaryMy: "Conflict ဆိုတာ Git က သင့်ရွေးချယ်မှုလိုတာပါ။ File ပြင်၊ stage လုပ်၊ commit လုပ်ပါ။",
        points: [
          { title: "Open", copy: "Find conflict markers." },
          { title: "Choose", copy: "Keep the correct lines." },
          { title: "Finish", copy: "Stage and commit the fix." },
        ],
        pointsMy: [
          { title: "ဖွင့်မယ်", copy: "Conflict marker ရှာပါ။" },
          { title: "ရွေးမယ်", copy: "မှန်တဲ့ lines ကိုထားပါ။" },
          { title: "ပြီးမယ်", copy: "Stage နဲ့ commit လုပ်ပါ။" },
        ],
        command: "git status",
        commandLabel: "Find conflicted files",
        commandLabelMy: "Conflict ဖြစ်တဲ့ file ရှာရန်",
        tip: "Ask your teammate before deleting their changes.",
        tipMy: "သူများ changes မဖျက်ခင် teammate ကိုမေးပါ။",
        challenge: "status",
        check: {
          question: "Is a merge conflict a broken repository?",
          options: ["No, it needs a choice", "Yes, always", "It deletes GitHub"],
          correct: 0,
          success: "Correct. Conflicts are normal and fixable.",
        },
        checkMy: {
          question: "Merge conflict က repository ပျက်တာလား။",
          options: ["မဟုတ်၊ ရွေးချယ်ရတာပါ", "အမြဲပျက်တယ်", "GitHub ဖျက်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ်။ Conflict က ပုံမှန်ဖြစ်ပြီး ဖြေရှင်းလို့ရတယ်။",
        },
      }),
    ],
  },
  {
    id: "github",
    number: "04",
    title: "Work on GitHub",
    description: "Connect a remote. Push work. Open and review pull requests.",
    duration: "28 min",
    difficulty: "Intermediate",
    my: {
      title: "GitHub မှာအတူလုပ်မယ်",
      description: "Remote ချိတ်မယ်။ Push လုပ်မယ်။ Pull request ဖွင့်ပြီး review လုပ်မယ်။",
      duration: "၂၈ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "connect-github",
        title: "Connect to GitHub",
        titleMy: "GitHub နဲ့ချိတ်မယ်",
        summary: "A remote connects your local repository to a repository on GitHub.",
        summaryMy: "Remote က local repository နဲ့ GitHub repository ကို ချိတ်ပေးတယ်။",
        points: [
          { title: "Create", copy: "Make an empty GitHub repository." },
          { title: "Copy", copy: "Copy its repository URL." },
          { title: "Connect", copy: "Add it as origin." },
        ],
        pointsMy: [
          { title: "ဖန်တီး", copy: "GitHub repository အလွတ်လုပ်ပါ။" },
          { title: "ကူးမယ်", copy: "Repository URL ကို copy လုပ်ပါ။" },
          { title: "ချိတ်မယ်", copy: "Origin အဖြစ်ထည့်ပါ။" },
        ],
        command: "git remote -v",
        commandLabel: "Check remote connections",
        commandLabelMy: "Remote connection ကြည့်ရန်",
        tip: "Origin is the common name for the main remote.",
        tipMy: "အဓိက remote ကို origin လို့ခေါ်လေ့ရှိတယ်။",
        challenge: "remote",
        check: {
          question: "What is a remote?",
          options: ["A linked online repository", "A commit message", "A branch color"],
          correct: 0,
          success: "Correct. A remote links your local work to GitHub.",
        },
        checkMy: {
          question: "Remote ဆိုတာ ဘာလဲ။",
          options: ["ချိတ်ထားတဲ့ online repository", "Commit message", "Branch အရောင်"],
          correct: 0,
          success: "မှန်ပါတယ်။ Local အလုပ်နဲ့ GitHub ကို ချိတ်ပေးတယ်။",
        },
      }),
      lesson({
        id: "push-pull",
        title: "Push and pull",
        titleMy: "Push နဲ့ pull လုပ်မယ်",
        summary: "Push sends commits to GitHub. Pull gets new commits from GitHub.",
        summaryMy: "Push က commits ကို GitHub တင်တယ်။ Pull က GitHub က commits အသစ်ယူတယ်။",
        points: [
          { title: "Pull", copy: "Get teammates' work first." },
          { title: "Push", copy: "Send your commits." },
          { title: "Check", copy: "Confirm on GitHub." },
        ],
        pointsMy: [
          { title: "Pull", copy: "Teammate အလုပ်ကို အရင်ယူပါ။" },
          { title: "Push", copy: "သင့် commits ကိုတင်ပါ။" },
          { title: "စစ်မယ်", copy: "GitHub မှာပြန်ကြည့်ပါ။" },
        ],
        command: "git push -u origin feat/community-guide",
        commandLabel: "Publish your branch",
        commandLabelMy: "Branch ကို GitHub တင်ရန်",
        tip: "Pull before you push shared branches.",
        tipMy: "Shared branch ကို push မလုပ်ခင် pull လုပ်ပါ။",
        challenge: "push",
        check: {
          question: "What does push do?",
          options: ["Sends commits to GitHub", "Gets commits", "Deletes a branch"],
          correct: 0,
          success: "Correct. Push publishes your local commits.",
        },
        checkMy: {
          question: "Push က ဘာလုပ်လဲ။",
          options: ["Commits ကို GitHub တင်တယ်", "Commits ယူတယ်", "Branch ဖျက်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ်။ Local commits ကို GitHub တင်တာပါ။",
        },
      }),
      lesson({
        id: "pull-requests",
        title: "Open a pull request",
        titleMy: "Pull request ဖွင့်မယ်",
        summary: "A pull request asks the team to review and merge your branch.",
        summaryMy: "Pull request က သင့် branch ကို review လုပ်ပြီး merge ဖို့ team ကိုတောင်းတာပါ။",
        points: [
          { title: "Explain", copy: "Say what and why." },
          { title: "Test", copy: "List how you checked it." },
          { title: "Review", copy: "Reply and make updates." },
        ],
        pointsMy: [
          { title: "ရှင်းပြ", copy: "ဘာနဲ့ ဘာကြောင့်ဆိုတာရေးပါ။" },
          { title: "Test", copy: "ဘယ်လိုစစ်ခဲ့လဲ ရေးပါ။" },
          { title: "Review", copy: "Reply လုပ်ပြီး update လုပ်ပါ။" },
        ],
        command: "git push -u origin feat/community-guide",
        commandLabel: "Push before opening a PR",
        commandLabelMy: "PR မဖွင့်ခင် push လုပ်ရန်",
        tip: "Small pull requests are faster to review.",
        tipMy: "Pull request သေးရင် review ပိုမြန်တယ်။",
        challenge: "push",
        check: {
          question: "What should a pull request explain?",
          options: ["What changed and why", "Your password", "Nothing"],
          correct: 0,
          success: "Correct. Help reviewers understand the change.",
        },
        checkMy: {
          question: "Pull request မှာ ဘာရှင်းပြသင့်လဲ။",
          options: ["ဘာပြောင်းပြီး ဘာကြောင့်လဲ", "Password", "ဘာမှမရေး"],
          correct: 0,
          success: "မှန်ပါတယ်။ Reviewer နားလည်အောင် ရေးပါ။",
        },
      }),
    ],
  },
  {
    id: "recovery",
    number: "05",
    title: "Fix mistakes",
    description: "Unstage files. Undo safely. Save unfinished work.",
    duration: "24 min",
    difficulty: "Intermediate",
    my: {
      title: "အမှားပြင်မယ်",
      description: "File unstage လုပ်မယ်။ လုံခြုံစွာ undo လုပ်မယ်။ မပြီးသေးတဲ့အလုပ် သိမ်းမယ်။",
      duration: "၂၄ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "restore-files",
        title: "Unstage a file",
        titleMy: "File ကို unstage လုပ်မယ်",
        summary: "Remove a file from the next commit without deleting its changes.",
        summaryMy: "File changes မဖျက်ဘဲ နောက် commit ထဲကနေ ဖယ်မယ်။",
        points: [
          { title: "Check", copy: "Find the staged file." },
          { title: "Restore", copy: "Remove it from staging." },
          { title: "Keep", copy: "Your file changes stay." },
        ],
        pointsMy: [
          { title: "စစ်မယ်", copy: "Staged file ကိုရှာပါ။" },
          { title: "ဖယ်မယ်", copy: "Staging ကနေ ဖယ်ပါ။" },
          { title: "ထားမယ်", copy: "File changes က မပျောက်ဘူး။" },
        ],
        command: "git restore --staged README.md",
        commandLabel: "Remove one file from staging",
        commandLabelMy: "File တစ်ခုကို staging မှဖယ်ရန်",
        tip: "Run status after every undo command.",
        tipMy: "Undo command လုပ်ပြီးတိုင်း status ကြည့်ပါ။",
        challenge: "restore",
        check: {
          question: "Does unstaging delete your edits?",
          options: ["No", "Yes", "Only on Friday"],
          correct: 0,
          success: "Correct. It only removes the file from staging.",
        },
        checkMy: {
          question: "Unstage လုပ်ရင် edit တွေပျောက်လား။",
          options: ["မပျောက်ပါ", "ပျောက်တယ်", "သောကြာနေ့ပဲ"],
          correct: 0,
          success: "မှန်ပါတယ်။ Staging ကနေပဲ ဖယ်တာပါ။",
        },
      }),
      lesson({
        id: "revert-commit",
        title: "Undo a shared commit",
        titleMy: "Share လုပ်ပြီး commit ကို undo မယ်",
        summary: "Revert creates a new commit that safely cancels an old one.",
        summaryMy: "Revert က commit အဟောင်းကို ပြန်ဖျက်တဲ့ commit အသစ်တစ်ခု ဖန်တီးတယ်။",
        points: [
          { title: "Find", copy: "Copy the commit ID." },
          { title: "Revert", copy: "Create the undo commit." },
          { title: "Push", copy: "Share the safe fix." },
        ],
        pointsMy: [
          { title: "ရှာမယ်", copy: "Commit ID ကို copy လုပ်ပါ။" },
          { title: "ပြန်မယ်", copy: "Undo commit ဖန်တီးပါ။" },
          { title: "တင်မယ်", copy: "Fix ကို push လုပ်ပါ။" },
        ],
        command: "git revert 4e8b6c1",
        commandLabel: "Safely reverse a commit",
        commandLabelMy: "Commit ကို လုံခြုံစွာပြန်ဖျက်ရန်",
        tip: "Use revert for commits already shared with others.",
        tipMy: "သူများနဲ့ share ပြီး commit ဆို revert သုံးပါ။",
        challenge: "revert",
        check: {
          question: "Best undo for a shared commit?",
          options: ["git revert", "Delete Git", "Remove GitHub"],
          correct: 0,
          success: "Correct. Revert keeps shared history safe.",
        },
        checkMy: {
          question: "Share ပြီး commit ကို ဘယ်လို undo လဲ။",
          options: ["git revert", "Git ဖျက်မယ်", "GitHub ဖယ်မယ်"],
          correct: 0,
          success: "မှန်ပါတယ်။ Revert က shared history ကိုလုံခြုံစေတယ်။",
        },
      }),
      lesson({
        id: "stash-reflog",
        title: "Save and find lost work",
        titleMy: "အလုပ်သိမ်းပြီး ပြန်ရှာမယ်",
        summary: "Stash pauses unfinished work. Reflog helps find commits that look lost.",
        summaryMy: "Stash က မပြီးသေးတဲ့အလုပ်ကို ခဏသိမ်းတယ်။ Reflog က ပျောက်သလိုဖြစ်တဲ့ commit ကိုရှာပေးတယ်။",
        points: [
          { title: "Stash", copy: "Pause unfinished edits." },
          { title: "Switch", copy: "Handle another task." },
          { title: "Return", copy: "Apply the saved edits." },
        ],
        pointsMy: [
          { title: "သိမ်းမယ်", copy: "မပြီးသေးတဲ့ edit ခဏသိမ်းပါ။" },
          { title: "ပြောင်းမယ်", copy: "တခြား task လုပ်ပါ။" },
          { title: "ပြန်ယူ", copy: "သိမ်းထားတဲ့ edit ပြန်ယူပါ။" },
        ],
        command: "git reflog",
        commandLabel: "Find recent Git activity",
        commandLabelMy: "မကြာသေးတဲ့ Git activity ရှာရန်",
        tip: "Git rarely loses committed work. Check reflog first.",
        tipMy: "Commit လုပ်ပြီးအလုပ် ပျောက်ခဲတယ်။ Reflog အရင်ကြည့်ပါ။",
        challenge: "reflog",
        check: {
          question: "Where can you find a lost commit?",
          options: ["git reflog", "git color", "git password"],
          correct: 0,
          success: "Correct. Reflog records recent HEAD movements.",
        },
        checkMy: {
          question: "ပျောက်သလိုဖြစ်တဲ့ commit ကို ဘယ်မှာရှာလဲ။",
          options: ["git reflog", "git color", "git password"],
          correct: 0,
          success: "မှန်ပါတယ်။ Reflog က မကြာသေးတဲ့ HEAD အပြောင်းအလဲပြတယ်။",
        },
      }),
    ],
  },
];

export const knowledgeTopics = [
  {
    id: "what-is-git",
    category: "Git basics",
    question: "What is Git?",
    answer: "Git is a tool that saves your project history. It shows what changed, who changed it, and when.",
    example: "You can return to yesterday’s working code after a mistake.",
    my: {
      category: "Git အခြေခံ",
      question: "Git ဆိုတာ ဘာလဲ။",
      answer: "Git က project history ကို သိမ်းပေးတဲ့ tool ပါ။ ဘာပြောင်းလဲ၊ ဘယ်သူပြင်၊ ဘယ်အချိန်ပြင်ဆိုတာ ကြည့်နိုင်တယ်။",
      example: "အမှားဖြစ်ရင် မနေ့က အလုပ်လုပ်တဲ့ code ကို ပြန်ယူနိုင်တယ်။",
    },
  },
  {
    id: "why-use-git",
    category: "Git basics",
    question: "Why do we use Git?",
    answer: "Git keeps work safe, records changes, and lets many people work on one project.",
    example: "You can test a new idea without losing the stable version.",
    my: {
      category: "Git အခြေခံ",
      question: "Git ကို ဘာကြောင့်သုံးလဲ။",
      answer: "အလုပ်ကို လုံခြုံစွာသိမ်းဖို့၊ changes မှတ်တမ်းထားဖို့၊ လူအများ project တစ်ခုမှာ အတူလုပ်ဖို့ သုံးတယ်။",
      example: "Stable version မပျောက်ဘဲ idea အသစ်ကို စမ်းနိုင်တယ်။",
    },
  },
  {
    id: "what-is-repository",
    category: "Git basics",
    question: "What is a repository?",
    answer: "A repository, or repo, is a project folder that Git is tracking. It includes files and their saved history.",
    example: "A website folder becomes a repo after you run git init.",
    my: {
      category: "Git အခြေခံ",
      question: "Repository (repo) ဆိုတာ ဘာလဲ။",
      answer: "Repo ဆိုတာ Git က စောင့်ကြည့်မှတ်တမ်းတင်နေတဲ့ project folder ပါ။ File တွေနဲ့ history ပါဝင်တယ်။",
      example: "Website folder မှာ git init run လုပ်ရင် repo ဖြစ်သွားတယ်။",
    },
  },
  {
    id: "what-is-commit",
    category: "Git basics",
    question: "What is a commit?",
    answer: "A commit is one saved snapshot of your project. It has an ID, author, time, and message.",
    example: "“Add login button” can be one commit.",
    my: {
      category: "Git အခြေခံ",
      question: "Commit ဆိုတာ ဘာလဲ။",
      answer: "Commit ဆိုတာ project ကို တစ်ကြိမ် snapshot သိမ်းထားတာပါ။ ID၊ author၊ အချိန်နဲ့ message ပါတယ်။",
      example: "“Add login button” က commit တစ်ခု ဖြစ်နိုင်တယ်။",
    },
  },
  {
    id: "what-is-branch",
    category: "Branches",
    question: "What is a branch?",
    answer: "A branch is a separate line of work. You can change code there without changing main.",
    example: "Build a search feature on feat/search while main stays stable.",
    my: {
      category: "Branch",
      question: "Branch ဆိုတာ ဘာလဲ။",
      answer: "Branch ဆိုတာ သီးခြားအလုပ်လမ်းကြောင်းတစ်ခုပါ။ Main ကို မပြောင်းဘဲ code အသစ်လုပ်နိုင်တယ်။",
      example: "Main ကိုတည်ငြိမ်ထားပြီး feat/search မှာ search feature လုပ်နိုင်တယ်။",
    },
  },
  {
    id: "why-use-branches",
    category: "Branches",
    question: "Why do we need branches?",
    answer: "Branches keep new or unfinished work away from stable code. They also make review easier.",
    example: "Each task or bug fix gets its own branch.",
    my: {
      category: "Branch",
      question: "Branch ကို ဘာကြောင့်လိုလဲ။",
      answer: "အသစ်လုပ်နေတဲ့အလုပ်ကို stable code နဲ့ခွဲထားဖို့ပါ။ Review လုပ်တာလည်း ပိုလွယ်တယ်။",
      example: "Task သို့ bug fix တစ်ခုစီအတွက် branch တစ်ခုသုံးပါ။",
    },
  },
  {
    id: "what-is-main",
    category: "Branches",
    question: "What is the main branch?",
    answer: "Main is usually the stable, trusted version of the project. Finished work is merged into it.",
    example: "Do not test risky unfinished work directly on main.",
    my: {
      category: "Branch",
      question: "Main branch ဆိုတာ ဘာလဲ။",
      answer: "Main က ပုံမှန်အားဖြင့် project ရဲ့ stable ဖြစ်ပြီး ယုံကြည်ရတဲ့ version ပါ။ ပြီးသွားတဲ့အလုပ်ကို main ထဲ merge လုပ်တယ်။",
      example: "မပြီးသေးတဲ့ risky အလုပ်ကို main မှာ တိုက်ရိုက်မစမ်းပါနဲ့။",
    },
  },
  {
    id: "git-vs-github",
    category: "GitHub",
    question: "Are Git and GitHub the same?",
    answer: "No. Git saves history on your computer. GitHub stores Git repositories online and adds team tools.",
    example: "Git works without internet. GitHub needs an internet connection.",
    my: {
      category: "GitHub",
      question: "Git နဲ့ GitHub တူလား။",
      answer: "မတူပါ။ Git က computer မှာ history သိမ်းတယ်။ GitHub က repo ကို online သိမ်းပြီး team tools ပေးတယ်။",
      example: "Git က internet မရှိလည်း အလုပ်လုပ်တယ်။ GitHub က internet လိုတယ်။",
    },
  },
  {
    id: "what-is-remote",
    category: "GitHub",
    question: "What is a remote?",
    answer: "A remote is the online copy connected to your local repository. The common remote name is origin.",
    example: "origin can point to your project on GitHub.",
    my: {
      category: "GitHub",
      question: "Remote ဆိုတာ ဘာလဲ။",
      answer: "Remote က local repo နဲ့ချိတ်ထားတဲ့ online copy ပါ။ အသုံးများတဲ့ remote name က origin ပါ။",
      example: "Origin က GitHub ပေါ်က သင့် project ကို ချိတ်ထားနိုင်တယ်။",
    },
  },
  {
    id: "clone-vs-fork",
    category: "GitHub",
    question: "What is the difference between clone and fork?",
    answer: "Clone downloads a repository to your computer. Fork creates your own GitHub copy of someone else’s repository.",
    example: "Fork first when you cannot push directly to the original project.",
    my: {
      category: "GitHub",
      question: "Clone နဲ့ fork ဘာကွာလဲ။",
      answer: "Clone က repo ကို computer ထဲ download လုပ်တယ်။ Fork က သူများ repo ကို သင့် GitHub အကောင့်ထဲ copy ဖန်တီးတယ်။",
      example: "မူရင်း project ကို push လုပ်ခွင့်မရှိရင် fork အရင်လုပ်ပါ။",
    },
  },
  {
    id: "push-vs-pull",
    category: "GitHub",
    question: "What do push and pull mean?",
    answer: "Push sends your commits to GitHub. Pull gets new commits from GitHub.",
    example: "Pull your teammate’s updates, then push your finished work.",
    my: {
      category: "GitHub",
      question: "Push နဲ့ pull ဆိုတာ ဘာလဲ။",
      answer: "Push က သင့် commits ကို GitHub တင်တယ်။ Pull က GitHub က commits အသစ်ကို ယူတယ်။",
      example: "Teammate update ကို pull လုပ်ပြီး သင့်အလုပ်ကို push လုပ်ပါ။",
    },
  },
  {
    id: "why-collaborate",
    category: "Collaboration",
    question: "Why do developers collaborate?",
    answer: "A team can build more, find mistakes earlier, share knowledge, and maintain a project together.",
    example: "One person builds the page while another reviews it and finds a bug.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Developer တွေ ဘာကြောင့် အတူလုပ်ကြလဲ။",
      answer: "အလုပ်ပိုလုပ်နိုင်ဖို့၊ အမှားစောစောရှာဖို့၊ အသိပညာမျှဝေဖို့နဲ့ project ကို အတူထိန်းသိမ်းဖို့ပါ။",
      example: "တစ်ယောက်က page လုပ်ပြီး နောက်တစ်ယောက်က review လုပ်ကာ bug ရှာနိုင်တယ်။",
    },
  },
  {
    id: "how-to-collaborate",
    category: "Collaboration",
    question: "How do we collaborate with GitHub?",
    answer: "Pull the latest work, create a branch, commit your task, push it, then open a pull request.",
    example: "Pull → branch → edit → commit → push → pull request.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "GitHub နဲ့ ဘယ်လိုအတူလုပ်လဲ။",
      answer: "Latest work ကို pull၊ branch ဖန်တီး၊ task commit၊ push၊ ပြီးရင် pull request ဖွင့်ပါ။",
      example: "Pull → branch → edit → commit → push → pull request။",
    },
  },
  {
    id: "what-is-pull-request",
    category: "Collaboration",
    question: "What is a pull request?",
    answer: "A pull request asks the team to review your branch and merge it into the main project.",
    example: "Explain what changed, why, and how you tested it.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Pull request ဆိုတာ ဘာလဲ။",
      answer: "သင့် branch ကို review လုပ်ပြီး main project ထဲ merge ဖို့ team ကို တောင်းတာပါ။",
      example: "ဘာပြောင်း၊ ဘာကြောင့်နဲ့ ဘယ်လို test လုပ်ခဲ့တယ်ဆိုတာ ရေးပါ။",
    },
  },
  {
    id: "what-is-code-review",
    category: "Collaboration",
    question: "What is code review?",
    answer: "Code review is when teammates read a change before merging it. They check quality, bugs, and clarity.",
    example: "Review the code, ask a question, or suggest a small fix.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Code review ဆိုတာ ဘာလဲ။",
      answer: "Merge မလုပ်ခင် teammate တွေက changes ကို ဖတ်ပြီး quality၊ bug နဲ့ ရှင်းလင်းမှု စစ်တာပါ။",
      example: "Code ဖတ်၊ မေးခွန်းမေး၊ သို့ fix အသေးစား အကြံပြုပါ။",
    },
  },
  {
    id: "what-is-merge",
    category: "Collaboration",
    question: "What does merge mean?",
    answer: "Merge combines changes from one branch into another branch.",
    example: "Merge feat/search into main after review.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Merge ဆိုတာ ဘာလဲ။",
      answer: "Branch တစ်ခုက changes ကို နောက် branch တစ်ခုထဲ ပေါင်းထည့်တာပါ။",
      example: "Review ပြီးရင် feat/search ကို main ထဲ merge လုပ်ပါ။",
    },
  },
  {
    id: "what-is-conflict",
    category: "Problems",
    question: "What is a merge conflict?",
    answer: "A conflict happens when Git cannot choose between two changes. A person must choose the correct result.",
    example: "Two people changed the same line in different ways.",
    my: {
      category: "ပြဿနာဖြေရှင်းခြင်း",
      question: "Merge conflict ဆိုတာ ဘာလဲ။",
      answer: "Changes နှစ်ခုထဲက ဘာယူရမလဲ Git မရွေးနိုင်တဲ့အခါ conflict ဖြစ်တယ်။ လူက မှန်တဲ့ result ကိုရွေးရတယ်။",
      example: "လူနှစ်ယောက်က line တစ်ခုတည်းကို ပုံစံမတူ ပြင်ထားတယ်။",
    },
  },
  {
    id: "mistake-safety",
    category: "Problems",
    question: "What if I make a mistake?",
    answer: "Stop and run git status. Most Git mistakes can be fixed. Do not run an unknown undo command quickly.",
    example: "Ask a teammate before rewriting shared history.",
    my: {
      category: "ပြဿနာဖြေရှင်းခြင်း",
      question: "အမှားလုပ်မိရင် ဘာလုပ်ရမလဲ။",
      answer: "ခဏရပ်ပြီး git status run ပါ။ Git အမှားအများစု ပြင်လို့ရတယ်။ မသိတဲ့ undo command ကို အမြန်မလုပ်ပါနဲ့။",
      example: "Shared history မပြောင်းခင် teammate ကိုမေးပါ။",
    },
  },
  {
    id: "need-internet",
    category: "Common questions",
    question: "Does Git need internet?",
    answer: "No. Local commands like add, commit, branch, and log work offline. GitHub push and pull need internet.",
    example: "You can commit on a plane and push when you are online.",
    my: {
      category: "မေးလေ့ရှိသည်",
      question: "Git သုံးဖို့ internet လိုလား။",
      answer: "မလိုပါ။ Add၊ commit၊ branch နဲ့ log က offline အလုပ်လုပ်တယ်။ GitHub push နဲ့ pull မှာ internet လိုတယ်။",
      example: "Internet မရှိချိန် commit လုပ်ပြီး online ရမှ push လုပ်နိုင်တယ်။",
    },
  },
  {
    id: "gitignore-readme",
    category: "Common questions",
    question: "What are README and .gitignore?",
    answer: "README explains the project. .gitignore tells Git which files not to track.",
    example: "Ignore secret .env files and explain setup steps in README.",
    my: {
      category: "မေးလေ့ရှိသည်",
      question: "README နဲ့ .gitignore ဆိုတာ ဘာလဲ။",
      answer: "README က project ကိုရှင်းပြတယ်။ .gitignore က ဘယ် file ကို Git မမှတ်တမ်းတင်ရမလဲ ပြောတယ်။",
      example: "Secret .env file ကို ignore လုပ်ပြီး setup အဆင့်ကို README မှာရေးပါ။",
    },
  },
  {
    id: "command-options",
    category: "Commands & delivery",
    question: "What does a dash option mean?",
    answer: "Options change how a command works. A short option uses one dash, such as -m. A long option uses two dashes, such as --message.",
    example: "git log --oneline shows each commit on one line.",
    my: {
      category: "Command နှင့် delivery",
      question: "Command မှာ dash option ဆိုတာ ဘာလဲ။",
      answer: "Option က command အလုပ်လုပ်ပုံကို ပြောင်းပေးတယ်။ Short option က -m လို dash တစ်ခု၊ long option က --message လို dash နှစ်ခုသုံးတယ်။",
      example: "git log --oneline က commit တစ်ခုကို line တစ်ကြောင်းနဲ့ပြတယ်။",
    },
  },
  {
    id: "flag-message",
    category: "Commands & delivery",
    question: "What does -m mean?",
    answer: "-m usually means message. With git commit, it lets you write the commit message in the same command.",
    example: "git commit -m \"Add search\"",
    my: {
      category: "Command နှင့် delivery",
      question: "-m ဆိုတာ ဘာလဲ။",
      answer: "-m က ပုံမှန်အားဖြင့် message ကိုဆိုလိုတယ်။ git commit မှာ commit message ကို command တစ်ကြောင်းတည်းနဲ့ ရေးနိုင်တယ်။",
      example: "git commit -m \"Add search\"",
    },
  },
  {
    id: "flag-verbose",
    category: "Commands & delivery",
    question: "What does -v mean?",
    answer: "-v usually means verbose. It asks a command to show more detail. The exact result depends on the command.",
    example: "git remote -v shows remote names and their full URLs.",
    my: {
      category: "Command နှင့် delivery",
      question: "-v ဆိုတာ ဘာလဲ။",
      answer: "-v က ပုံမှန်အားဖြင့် verbose၊ အသေးစိတ်ပိုပြတာကို ဆိုလိုတယ်။ Result က သုံးတဲ့ command ပေါ်မူတည်တယ်။",
      example: "git remote -v က remote name နဲ့ URL အပြည့်ပြတယ်။",
    },
  },
  {
    id: "what-is-package",
    category: "Commands & delivery",
    question: "What is a package?",
    answer: "A package is reusable code or a bundled application. Projects install packages instead of rebuilding every tool from zero.",
    example: "A React project can install a date-formatting package with npm.",
    my: {
      category: "Command နှင့် delivery",
      question: "Package ဆိုတာ ဘာလဲ။",
      answer: "Package ဆိုတာ ပြန်သုံးလို့ရတဲ့ code သို့ စုစည်းထားတဲ့ application ပါ။ Tool တိုင်းကို အစကမရေးဘဲ package install လုပ်သုံးတယ်။",
      example: "React project မှာ date format package ကို npm နဲ့ install လုပ်နိုင်တယ်။",
    },
  },
  {
    id: "what-is-release",
    category: "Commands & delivery",
    question: "What is a release?",
    answer: "A release is a named, tested version of the project that is ready for people to use.",
    example: "Version 1.2.0 can be a release with new features and release notes.",
    my: {
      category: "Command နှင့် delivery",
      question: "Release ဆိုတာ ဘာလဲ။",
      answer: "Release ဆိုတာ လူတွေသုံးဖို့ အဆင်သင့်ဖြစ်တဲ့ name နဲ့ version ပါတဲ့ စမ်းသပ်ပြီး project version တစ်ခုပါ။",
      example: "Feature အသစ်နဲ့ release notes ပါတဲ့ Version 1.2.0 က release တစ်ခုပါ။",
    },
  },
  {
    id: "what-is-deploy",
    category: "Commands & delivery",
    question: "What does deploy mean?",
    answer: "Deploy means putting a tested application on a server so users can open and use it.",
    example: "Deploy a website after its build and tests pass.",
    my: {
      category: "Command နှင့် delivery",
      question: "Deploy ဆိုတာ ဘာလဲ။",
      answer: "Deploy ဆိုတာ test လုပ်ပြီး application ကို user တွေဖွင့်သုံးနိုင်အောင် server ပေါ်တင်တာပါ။",
      example: "Website build နဲ့ test အောင်မြင်ပြီးမှ deploy လုပ်ပါ။",
    },
  },
  {
    id: "release-vs-deploy",
    category: "Commands & delivery",
    question: "Are release and deploy the same?",
    answer: "No. A release is a prepared version. A deploy puts a version into an environment where it runs.",
    example: "Create release 1.2.0 today and deploy it to production tomorrow.",
    my: {
      category: "Command နှင့် delivery",
      question: "Release နဲ့ deploy တူလား။",
      answer: "မတူပါ။ Release က အဆင်သင့်ပြင်ထားတဲ့ version ပါ။ Deploy က အဲဒီ version ကို အလုပ်လုပ်မယ့် environment ပေါ်တင်တာပါ။",
      example: "ဒီနေ့ release 1.2.0 ဖန်တီးပြီး မနက်ဖြန် production ကို deploy လုပ်နိုင်တယ်။",
    },
  },
  {
    id: "what-is-cicd",
    category: "Commands & delivery",
    question: "What is CI/CD?",
    answer: "CI automatically builds and tests each change. CD automatically prepares or deploys changes after the checks pass.",
    example: "A pull request starts tests. A merge to main can start a deployment.",
    my: {
      category: "Command နှင့် delivery",
      question: "CI/CD ဆိုတာ ဘာလဲ။",
      answer: "CI က change တိုင်းကို အလိုအလျောက် build နဲ့ test လုပ်တယ်။ CD က check အောင်မြင်ရင် release ပြင်ဆင် သို့ deploy လုပ်တယ်။",
      example: "Pull request ဖွင့်ရင် test စတယ်။ Main ကို merge လုပ်ရင် deployment စနိုင်တယ်။",
    },
  },
];
