const lesson = ({
  id,
  title,
  titleMy,
  summary,
  summaryMy,
  command,
  commandLabel,
  commandLabelMy,
  tip,
  tipMy,
  challenge,
  readTime = "4 min",
  points,
  pointsMy,
  check,
  checkMy,
}) => ({
  id,
  title,
  eyebrow: "Step-by-step",
  readTime,
  summary,
  points,
  command,
  commandLabel,
  tip,
  challenge,
  check,
  my: {
    title: titleMy,
    eyebrow: "တစ်ဆင့်ချင်း လေ့လာမယ်",
    readTime: readTime.replace("min", "မိနစ်"),
    summary: summaryMy,
    points: pointsMy,
    commandLabel: commandLabelMy,
    tip: tipMy,
    check: checkMy,
  },
});

export const modules = [
  {
    id: "foundations",
    number: "01",
    title: "Git basics",
    description: "Know what Git saves. Set it up. Make your first repository.",
    duration: "18 min",
    difficulty: "Beginner",
    my: {
      title: "Git အခြေခံ",
      description: "Git က ဘာသိမ်းသလဲ သိမယ် Setup လုပ်မယ် ပထမ repository ဖန်တီးမယ်",
      duration: "၁၈ မိနစ်",
      difficulty: "အစပြုသူ",
    },
    lessons: [
      lesson({
        id: "what-is-git",
        title: "What Git saves",
        titleMy: "Git က ဘာသိမ်းသလဲ",
        summary: "Git saves project snapshots. You can see changes, return to old work, and work safely.",
        summaryMy: "Git က project အခြေအနေကို မှတ်တမ်းတင်ပေးတယ် ပြောင်းလဲမှုကြည့်၊ အဟောင်းပြန်ယူ၊ စိတ်ချစွာ လုပ်နိုင်တယ်",
        points: [
          { title: "Edit", copy: "Change files in your project." },
          { title: "Stage", copy: "Choose changes to save next." },
          { title: "Commit", copy: "Save one clear snapshot." },
        ],
        pointsMy: [
          { title: "ပြင်မယ်", copy: "Project file တွေကို ပြင်မယ်" },
          { title: "ရွေးမယ်", copy: "သိမ်းမယ့် changes ကို ရွေးမယ်" },
          { title: "သိမ်းမယ်", copy: "Commit တစ်ခုအဖြစ် သိမ်းမယ်" },
        ],
        command: "git status",
        commandLabel: "Check your project",
        commandLabelMy: "Project အခြေအနေကြည့်ရန်",
        tip: "Run git status whenever you are unsure.",
        tipMy: "မသေချာတိုင်း git status ကို run ပါ",
        challenge: "status",
        check: {
          question: "What does a commit save?",
          options: ["A project snapshot", "A GitHub password", "A new computer"],
          correct: 0,
          success: "Correct. A commit is a saved project snapshot.",
        },
        checkMy: {
          question: "Commit က ဘာကိုသိမ်းသလဲ",
          options: ["Project snapshot", "GitHub password", "Computer အသစ်"],
          correct: 0,
          success: "မှန်ပါတယ် Commit က project snapshot တစ်ခုပါ",
        },
      }),
      lesson({
        id: "setup-git",
        title: "Set your name and email",
        titleMy: "Name နဲ့ email ထည့်မယ်",
        summary: "Git adds your name and email to each commit. Set them once on your computer.",
        summaryMy: "Git က commit တိုင်းမှာ သင့် name နဲ့ email ထည့်တယ် Computer မှာ တစ်ကြိမ် setup လုပ်ရုံပါ",
        points: [
          { title: "Name", copy: "Use the name your team knows." },
          { title: "Email", copy: "Use your GitHub email." },
          { title: "Check", copy: "List the saved settings." },
        ],
        pointsMy: [
          { title: "Name", copy: "Team က သိတဲ့ name ကိုသုံးပါ" },
          { title: "Email", copy: "GitHub email ကိုသုံးပါ" },
          { title: "စစ်မယ်", copy: "သိမ်းထားတဲ့ setting ကိုကြည့်ပါ" },
        ],
        command: 'git config --global user.name "Your Name"',
        commandLabel: "Set your Git name",
        commandLabelMy: "Git name ထည့်ရန်",
        tip: "This name is public when you push commits to GitHub.",
        tipMy: "GitHub ကို push လုပ်ရင် ဒီ name ကို အများမြင်နိုင်တယ်",
        challenge: "config",
        check: {
          question: "How often do you set the global name?",
          options: ["Usually once", "Before every commit", "Never"],
          correct: 0,
          success: "Right. Global settings normally need to be set once.",
        },
        checkMy: {
          question: "Global name ကို ဘယ်နှကြိမ် ထည့်ရမလဲ",
          options: ["ပုံမှန် တစ်ကြိမ်", "Commit တိုင်းမတိုင်ခင်", "မထည့်ရ"],
          correct: 0,
          success: "မှန်ပါတယ် ပုံမှန် တစ်ကြိမ် setup လုပ်ရုံပါ",
        },
      }),
      lesson({
        id: "first-repository",
        title: "Create a repository",
        titleMy: "Repository ဖန်တီးမယ်",
        summary: "Turn a normal project folder into a Git repository with one command.",
        summaryMy: "သာမန် project folder ကို command တစ်ခုနဲ့ Git repository ပြောင်းမယ်",
        points: [
          { title: "Open", copy: "Open your project folder." },
          { title: "Initialize", copy: "Run git init once." },
          { title: "Confirm", copy: "Run git status." },
        ],
        pointsMy: [
          { title: "ဖွင့်မယ်", copy: "Project folder ကိုဖွင့်ပါ" },
          { title: "စမယ်", copy: "git init တစ်ကြိမ် run ပါ" },
          { title: "စစ်မယ်", copy: "git status run ပါ" },
        ],
        command: "git init",
        commandLabel: "Start Git in this folder",
        commandLabelMy: "ဒီ folder မှာ Git စရန်",
        tip: "Do not run git init inside another Git repository.",
        tipMy: "Git repository တစ်ခုအတွင်းမှာ git init ထပ်မလုပ်ပါနဲ့",
        challenge: "init",
        check: {
          question: "Which command starts a repository?",
          options: ["git init", "git start", "git new"],
          correct: 0,
          success: "Correct. git init starts Git in the current folder.",
        },
        checkMy: {
          question: "Repository စတဲ့ command က ဘာလဲ",
          options: ["git init", "git start", "git new"],
          correct: 0,
          success: "မှန်ပါတယ် git init က လက်ရှိ folder မှာ Git စပေးတယ်",
        },
      }),
    ],
  },
  {
    id: "daily-workflow",
    number: "02",
    title: "Save daily work",
    description: "Check changes. Stage the right files. Make clean commits.",
    duration: "22 min",
    difficulty: "Beginner",
    my: {
      title: "နေ့စဉ်အလုပ် သိမ်းမယ်",
      description: "Changes ကြည့်မယ် File ရွေးမယ် သန့်ရှင်းတဲ့ commit လုပ်မယ်",
      duration: "၂၂ မိနစ်",
      difficulty: "အစပြုသူ",
    },
    lessons: [
      lesson({
        id: "check-changes",
        title: "Check changed files",
        titleMy: "ပြောင်းထားတဲ့ file ကြည့်မယ်",
        summary: "Check before you save. Git shows changed, new, and staged files.",
        summaryMy: "မသိမ်းခင် အရင်စစ်ပါ Git က ပြင်ထား၊ အသစ်ထည့်၊ ရွေးထားတဲ့ file တွေပြမယ်",
        points: [
          { title: "Red", copy: "Changed but not staged." },
          { title: "Green", copy: "Ready for the next commit." },
          { title: "Clean", copy: "No unsaved changes." },
        ],
        pointsMy: [
          { title: "အနီ", copy: "ပြင်ထားပေမယ့် မရွေးရသေး" },
          { title: "အစိမ်း", copy: "Commit လုပ်ဖို့ အဆင်သင့်" },
          { title: "ရှင်းနေ", copy: "မသိမ်းရသေးတာ မရှိ" },
        ],
        command: "git status",
        commandLabel: "See changed files",
        commandLabelMy: "ပြောင်းထားတဲ့ file ကြည့်ရန်",
        tip: "Read the status output from top to bottom.",
        tipMy: "Status output ကို အပေါ်ကနေ အောက်ထိဖတ်ပါ",
        challenge: "status",
        check: {
          question: "When should you run git status?",
          options: ["Before and after changes", "Only once a year", "Only on GitHub"],
          correct: 0,
          success: "Correct. Check status often.",
        },
        checkMy: {
          question: "git status ကို ဘယ်အချိန် run သင့်လဲ",
          options: ["အလုပ်မလုပ်ခင်နဲ့ လုပ်ပြီး", "တစ်နှစ်တစ်ကြိမ်", "GitHub မှာပဲ"],
          correct: 0,
          success: "မှန်ပါတယ် Status ကို မကြာခဏကြည့်ပါ",
        },
      }),
      lesson({
        id: "stage-files",
        title: "Choose files to save",
        titleMy: "သိမ်းမယ့် file ရွေးမယ်",
        summary: "Staging lets you choose exactly what goes into the next commit.",
        summaryMy: "Staging က နောက် commit မှာ ပါမယ့် file ကို တိတိကျကျ ရွေးပေးတယ်",
        points: [
          { title: "Review", copy: "Check the file list." },
          { title: "Add", copy: "Stage one file or all files." },
          { title: "Check", copy: "Run status again." },
        ],
        pointsMy: [
          { title: "ကြည့်မယ်", copy: "File list ကိုအရင်စစ်ပါ" },
          { title: "ထည့်မယ်", copy: "File တစ်ခု သို့ အားလုံးရွေးပါ" },
          { title: "ပြန်စစ်", copy: "Status ထပ်ကြည့်ပါ" },
        ],
        command: "git add .",
        commandLabel: "Stage all current changes",
        commandLabelMy: "လက်ရှိ changes အားလုံးရွေးရန်",
        tip: "For clean commits, stage only files for one task.",
        tipMy: "Commit သန့်ဖို့ task တစ်ခုနဲ့ဆိုင်တဲ့ file ပဲရွေးပါ",
        challenge: "add",
        check: {
          question: "What does staging do?",
          options: ["Selects the next changes", "Deletes the project", "Uploads to GitHub"],
          correct: 0,
          success: "Correct. Staging selects changes for the next commit.",
        },
        checkMy: {
          question: "Staging က ဘာလုပ်သလဲ",
          options: ["နောက် changes ကိုရွေးတယ်", "Project ဖျက်တယ်", "GitHub တင်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ် နောက် commit ထဲက changes ကိုရွေးတာပါ",
        },
      }),
      lesson({
        id: "make-commit",
        title: "Make a clear commit",
        titleMy: "ရှင်းလင်းတဲ့ commit လုပ်မယ်",
        summary: "A commit saves staged work. Use a short message that says what changed.",
        summaryMy: "Commit က ရွေးထားတဲ့အလုပ်ကို သိမ်းတယ် ဘာပြောင်းလဲဆိုတာ message တိုတိုရေးပါ",
        points: [
          { title: "One task", copy: "Keep one idea per commit." },
          { title: "Short message", copy: "Start with an action word." },
          { title: "Confirm", copy: "Check the new commit." },
        ],
        pointsMy: [
          { title: "Task တစ်ခု", copy: "Commit တစ်ခုမှာ idea တစ်ခုပဲ" },
          { title: "Message တိုတို", copy: "လုပ်ဆောင်ချက်နဲ့ စရေးပါ" },
          { title: "စစ်မယ်", copy: "Commit အသစ်ကိုကြည့်ပါ" },
        ],
        command: 'git commit -m "Add contributor guide"',
        commandLabel: "Save the staged changes",
        commandLabelMy: "ရွေးထားတဲ့ changes သိမ်းရန်",
        tip: "Good: Add search button. Avoid: update stuff.",
        tipMy: "ကောင်း: Add search button မကောင်း: update stuff",
        challenge: "commit",
        check: {
          question: "Which message is clearer?",
          options: ["Add profile button", "changes", "work"],
          correct: 0,
          success: "Correct. Say exactly what the commit changes.",
        },
        checkMy: {
          question: "ဘယ် message က ပိုရှင်းလဲ",
          options: ["Add profile button", "changes", "work"],
          correct: 0,
          success: "မှန်ပါတယ် ဘာပြောင်းလဲဆိုတာ တိတိကျကျရေးပါ",
        },
      }),
    ],
  },
  {
    id: "branching",
    number: "03",
    title: "Use branches",
    description: "Create a branch. Merge code, rebase safely, and solve conflicts.",
    duration: "34 min",
    difficulty: "Intermediate",
    my: {
      title: "Branch သုံးမယ်",
      description: "Branch ဖန်တီးမယ် Code merge၊ rebase နဲ့ conflict ဖြေရှင်းမယ်",
      duration: "၃၄ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "create-branch",
        title: "Create a work branch",
        titleMy: "အလုပ် branch ဖန်တီးမယ်",
        summary: "Use a branch for each task. Your main branch stays stable.",
        summaryMy: "Task တစ်ခုစီအတွက် branch တစ်ခုသုံးပါ Main branch က တည်ငြိမ်နေမယ်",
        points: [
          { title: "Update main", copy: "Start from current work." },
          { title: "Create", copy: "Use a clear branch name." },
          { title: "Work", copy: "Commit on the new branch." },
        ],
        pointsMy: [
          { title: "Main update", copy: "လက်ရှိအလုပ်ကနေ စပါ" },
          { title: "ဖန်တီး", copy: "ရှင်းတဲ့ branch name သုံးပါ" },
          { title: "လုပ်မယ်", copy: "Branch အသစ်မှာ commit လုပ်ပါ" },
        ],
        command: "git switch -c feat/community-guide",
        commandLabel: "Create and switch branch",
        commandLabelMy: "Branch ဖန်တီးပြီး ပြောင်းရန်",
        tip: "Use names like feat/search or fix/menu.",
        tipMy: "feat/search သို့ fix/menu လို name သုံးပါ",
        challenge: "branch",
        check: {
          question: "Why use a feature branch?",
          options: ["Keep main stable", "Make Git slower", "Delete history"],
          correct: 0,
          success: "Correct. A branch gives your task a safe place.",
        },
        checkMy: {
          question: "Feature branch ဘာကြောင့်သုံးလဲ",
          options: ["Main ကိုတည်ငြိမ်စေဖို့", "Git နှေးစေဖို့", "History ဖျက်ဖို့"],
          correct: 0,
          success: "မှန်ပါတယ် Task အတွက် လုံခြုံတဲ့နေရာရတယ်",
        },
      }),
      lesson({
        id: "switch-merge",
        title: "Merge code safely",
        titleMy: "Code ကို လုံခြုံစွာ merge လုပ်မယ်",
        summary: "Review and test the branch. Then return to main and merge the finished code.",
        summaryMy: "Branch ကို review နဲ့ test လုပ်ပါ ပြီးရင် main ကိုပြန်ပြီး code ကို merge လုပ်ပါ",
        points: [
          { title: "Commit", copy: "Save all task work." },
          { title: "Switch", copy: "Return to main." },
          { title: "Merge", copy: "Bring the branch into main." },
        ],
        pointsMy: [
          { title: "Commit", copy: "Task အလုပ်အားလုံး သိမ်းပါ" },
          { title: "ပြောင်းမယ်", copy: "Main ကိုပြန်ပါ" },
          { title: "ပေါင်းမယ်", copy: "Branch ကို main ထဲထည့်ပါ" },
        ],
        command: "git merge feat/community-guide",
        commandLabel: "Merge the finished branch",
        commandLabelMy: "ပြီးသွားတဲ့ branch ကို merge ရန်",
        tip: "Run tests before and after merging.",
        tipMy: "Merge မလုပ်ခင်နဲ့ လုပ်ပြီး test run ပါ",
        challenge: "merge",
        check: {
          question: "Where do you merge a finished feature?",
          options: ["Into main", "Into the recycle bin", "Into an email"],
          correct: 0,
          success: "Correct. Switch to main, then merge the feature.",
        },
        checkMy: {
          question: "ပြီးသွားတဲ့ feature ကို ဘယ်မှာ merge လုပ်လဲ",
          options: ["Main ထဲ", "Recycle bin ထဲ", "Email ထဲ"],
          correct: 0,
          success: "မှန်ပါတယ် Main ကိုပြောင်းပြီး feature ကို merge လုပ်ပါ",
        },
      }),
      lesson({
        id: "rebase-branch",
        title: "Rebase your branch",
        titleMy: "Branch ကို rebase လုပ်မယ်",
        summary: "Rebase moves your branch commits on top of the newest main. This creates a clean, straight history.",
        summaryMy: "Rebase က သင့် branch commits ကို main အသစ်ဆုံးအပေါ် ရွှေ့တင်တယ် History က ရှင်းပြီး တစ်ကြောင်းတည်းဖြစ်တယ်",
        points: [
          { title: "Update", copy: "Get the newest main branch." },
          { title: "Rebase", copy: "Move your commits onto main." },
          { title: "Test", copy: "Check the code before pushing." },
        ],
        pointsMy: [
          { title: "Update", copy: "Main branch အသစ်ဆုံးကို ယူပါ" },
          { title: "Rebase", copy: "သင့် commits ကို main အပေါ်ရွှေ့ပါ" },
          { title: "Test", copy: "Push မလုပ်ခင် code ကိုစစ်ပါ" },
        ],
        command: "git rebase main",
        commandLabel: "Move this branch onto main",
        commandLabelMy: "ဒီ branch ကို main အပေါ်ရွှေ့ရန်",
        tip: "Rebase your own local branch. Do not rebase shared branches unless the team agrees.",
        tipMy: "ကိုယ့် local branch ကို rebase လုပ်ပါ Team သဘောမတူဘဲ shared branch ကို rebase မလုပ်ပါနဲ့",
        challenge: "rebase",
        check: {
          question: "What does rebase change?",
          options: ["Commit history", "GitHub password", "File names only"],
          correct: 0,
          success: "Correct. Rebase rewrites where your branch commits begin.",
        },
        checkMy: {
          question: "Rebase က ဘာကိုပြောင်းလဲသလဲ",
          options: ["Commit history", "GitHub password", "File name ပဲ"],
          correct: 0,
          success: "မှန်ပါတယ် Branch commits စတဲ့နေရာကို rebase က ပြန်ရေးတယ်",
        },
      }),
      lesson({
        id: "merge-conflicts",
        title: "Solve a code conflict",
        titleMy: "Code conflict ဖြေရှင်းမယ်",
        summary: "A conflict means two changes overlap. Read both versions, choose the correct code, then test it.",
        summaryMy: "Conflict ဆိုတာ changes နှစ်ခု ထပ်နေတာပါ Version နှစ်ခုလုံးဖတ်၊ မှန်တဲ့ code ရွေးပြီး test လုပ်ပါ",
        points: [
          { title: "Open", copy: "Find conflict markers." },
          { title: "Choose", copy: "Keep the correct lines." },
          { title: "Finish", copy: "Stage and commit the fix." },
        ],
        pointsMy: [
          { title: "ဖွင့်မယ်", copy: "Conflict marker ရှာပါ" },
          { title: "ရွေးမယ်", copy: "မှန်တဲ့ lines ကိုထားပါ" },
          { title: "ပြီးမယ်", copy: "Stage နဲ့ commit လုပ်ပါ" },
        ],
        command: "git status",
        commandLabel: "Find conflicted files",
        commandLabelMy: "Conflict ဖြစ်တဲ့ file ရှာရန်",
        tip: "Ask your teammate before deleting their changes.",
        tipMy: "သူများ changes မဖျက်ခင် teammate ကိုမေးပါ",
        challenge: "status",
        check: {
          question: "Is a merge conflict a broken repository?",
          options: ["No, it needs a choice", "Yes, always", "It deletes GitHub"],
          correct: 0,
          success: "Correct. Conflicts are normal and fixable.",
        },
        checkMy: {
          question: "Merge conflict က repository ပျက်တာလား",
          options: ["မဟုတ်၊ ရွေးချယ်ရတာပါ", "အမြဲပျက်တယ်", "GitHub ဖျက်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ် Conflict က ပုံမှန်ဖြစ်ပြီး ဖြေရှင်းလို့ရတယ်",
        },
      }),
    ],
  },
  {
    id: "github",
    number: "04",
    title: "Work on GitHub",
    description: "Connect a remote. Push work. Open and review pull requests.",
    duration: "28 min",
    difficulty: "Intermediate",
    my: {
      title: "GitHub မှာအတူလုပ်မယ်",
      description: "Remote ချိတ်မယ် Push လုပ်မယ် Pull request ဖွင့်ပြီး review လုပ်မယ်",
      duration: "၂၈ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "connect-github",
        title: "Connect to GitHub",
        titleMy: "GitHub နဲ့ချိတ်မယ်",
        summary: "A remote connects your local repository to a repository on GitHub.",
        summaryMy: "Remote က local repository နဲ့ GitHub repository ကို ချိတ်ပေးတယ်",
        points: [
          { title: "Create", copy: "Make an empty GitHub repository." },
          { title: "Copy", copy: "Copy its repository URL." },
          { title: "Connect", copy: "Add it as origin." },
        ],
        pointsMy: [
          { title: "ဖန်တီး", copy: "GitHub repository အလွတ်လုပ်ပါ" },
          { title: "ကူးမယ်", copy: "Repository URL ကို copy လုပ်ပါ" },
          { title: "ချိတ်မယ်", copy: "Origin အဖြစ်ထည့်ပါ" },
        ],
        command: "git remote -v",
        commandLabel: "Check remote connections",
        commandLabelMy: "Remote connection ကြည့်ရန်",
        tip: "Origin is the common name for the main remote.",
        tipMy: "အဓိက remote ကို origin လို့ခေါ်လေ့ရှိတယ်",
        challenge: "remote",
        check: {
          question: "What is a remote?",
          options: ["A linked online repository", "A commit message", "A branch color"],
          correct: 0,
          success: "Correct. A remote links your local work to GitHub.",
        },
        checkMy: {
          question: "Remote ဆိုတာ ဘာလဲ",
          options: ["ချိတ်ထားတဲ့ online repository", "Commit message", "Branch အရောင်"],
          correct: 0,
          success: "မှန်ပါတယ် Local အလုပ်နဲ့ GitHub ကို ချိတ်ပေးတယ်",
        },
      }),
      lesson({
        id: "push-pull",
        title: "Push and pull",
        titleMy: "Push နဲ့ pull လုပ်မယ်",
        summary: "Push sends commits to GitHub. Pull gets new commits from GitHub.",
        summaryMy: "Push က commits ကို GitHub တင်တယ် Pull က GitHub က commits အသစ်ယူတယ်",
        points: [
          { title: "Pull", copy: "Get teammates' work first." },
          { title: "Push", copy: "Send your commits." },
          { title: "Check", copy: "Confirm on GitHub." },
        ],
        pointsMy: [
          { title: "Pull", copy: "Teammate အလုပ်ကို အရင်ယူပါ" },
          { title: "Push", copy: "သင့် commits ကိုတင်ပါ" },
          { title: "စစ်မယ်", copy: "GitHub မှာပြန်ကြည့်ပါ" },
        ],
        command: "git push -u origin feat/community-guide",
        commandLabel: "Publish your branch",
        commandLabelMy: "Branch ကို GitHub တင်ရန်",
        tip: "Pull before you push shared branches.",
        tipMy: "Shared branch ကို push မလုပ်ခင် pull လုပ်ပါ",
        challenge: "push",
        check: {
          question: "What does push do?",
          options: ["Sends commits to GitHub", "Gets commits", "Deletes a branch"],
          correct: 0,
          success: "Correct. Push publishes your local commits.",
        },
        checkMy: {
          question: "Push က ဘာလုပ်လဲ",
          options: ["Commits ကို GitHub တင်တယ်", "Commits ယူတယ်", "Branch ဖျက်တယ်"],
          correct: 0,
          success: "မှန်ပါတယ် Local commits ကို GitHub တင်တာပါ",
        },
      }),
      lesson({
        id: "pull-requests",
        title: "Open a pull request",
        titleMy: "Pull request ဖွင့်မယ်",
        summary: "A pull request asks the team to review and merge your branch.",
        summaryMy: "Pull request က သင့် branch ကို review လုပ်ပြီး merge ဖို့ team ကိုတောင်းတာပါ",
        points: [
          { title: "Explain", copy: "Say what and why." },
          { title: "Test", copy: "List how you checked it." },
          { title: "Review", copy: "Reply and make updates." },
        ],
        pointsMy: [
          { title: "ရှင်းပြ", copy: "ဘာနဲ့ ဘာကြောင့်ဆိုတာရေးပါ" },
          { title: "Test", copy: "ဘယ်လိုစစ်ခဲ့လဲ ရေးပါ" },
          { title: "Review", copy: "Reply လုပ်ပြီး update လုပ်ပါ" },
        ],
        command: "git push -u origin feat/community-guide",
        commandLabel: "Push before opening a PR",
        commandLabelMy: "PR မဖွင့်ခင် push လုပ်ရန်",
        tip: "Small pull requests are faster to review.",
        tipMy: "Pull request သေးရင် review ပိုမြန်တယ်",
        challenge: "push",
        check: {
          question: "What should a pull request explain?",
          options: ["What changed and why", "Your password", "Nothing"],
          correct: 0,
          success: "Correct. Help reviewers understand the change.",
        },
        checkMy: {
          question: "Pull request မှာ ဘာရှင်းပြသင့်လဲ",
          options: ["ဘာပြောင်းပြီး ဘာကြောင့်လဲ", "Password", "ဘာမှမရေး"],
          correct: 0,
          success: "မှန်ပါတယ် Reviewer နားလည်အောင် ရေးပါ",
        },
      }),
    ],
  },
  {
    id: "recovery",
    number: "05",
    title: "Fix mistakes",
    description: "Unstage, undo, recover work, and solve Git problems safely.",
    duration: "30 min",
    difficulty: "Intermediate",
    my: {
      title: "အမှားပြင်မယ်",
      description: "Unstage၊ undo၊ recovery နဲ့ Git ပြဿနာကို လုံခြုံစွာ ဖြေရှင်းမယ်",
      duration: "၃၀ မိနစ်",
      difficulty: "အလယ်အလတ်",
    },
    lessons: [
      lesson({
        id: "restore-files",
        title: "Unstage a file",
        titleMy: "File ကို unstage လုပ်မယ်",
        summary: "Remove a file from the next commit without deleting its changes.",
        summaryMy: "File changes မဖျက်ဘဲ နောက် commit ထဲကနေ ဖယ်မယ်",
        points: [
          { title: "Check", copy: "Find the staged file." },
          { title: "Restore", copy: "Remove it from staging." },
          { title: "Keep", copy: "Your file changes stay." },
        ],
        pointsMy: [
          { title: "စစ်မယ်", copy: "Staged file ကိုရှာပါ" },
          { title: "ဖယ်မယ်", copy: "Staging ကနေ ဖယ်ပါ" },
          { title: "ထားမယ်", copy: "File changes က မပျောက်ဘူး" },
        ],
        command: "git restore --staged README.md",
        commandLabel: "Remove one file from staging",
        commandLabelMy: "File တစ်ခုကို staging မှဖယ်ရန်",
        tip: "Run status after every undo command.",
        tipMy: "Undo command လုပ်ပြီးတိုင်း status ကြည့်ပါ",
        challenge: "restore",
        check: {
          question: "Does unstaging delete your edits?",
          options: ["No", "Yes", "Only on Friday"],
          correct: 0,
          success: "Correct. It only removes the file from staging.",
        },
        checkMy: {
          question: "Unstage လုပ်ရင် edit တွေပျောက်လား",
          options: ["မပျောက်ပါ", "ပျောက်တယ်", "သောကြာနေ့ပဲ"],
          correct: 0,
          success: "မှန်ပါတယ် Staging ကနေပဲ ဖယ်တာပါ",
        },
      }),
      lesson({
        id: "revert-commit",
        title: "Undo a shared commit",
        titleMy: "Share လုပ်ပြီး commit ကို undo မယ်",
        summary: "Revert creates a new commit that safely cancels an old one.",
        summaryMy: "Revert က commit အဟောင်းကို ပြန်ဖျက်တဲ့ commit အသစ်တစ်ခု ဖန်တီးတယ်",
        points: [
          { title: "Find", copy: "Copy the commit ID." },
          { title: "Revert", copy: "Create the undo commit." },
          { title: "Push", copy: "Share the safe fix." },
        ],
        pointsMy: [
          { title: "ရှာမယ်", copy: "Commit ID ကို copy လုပ်ပါ" },
          { title: "ပြန်မယ်", copy: "Undo commit ဖန်တီးပါ" },
          { title: "တင်မယ်", copy: "Fix ကို push လုပ်ပါ" },
        ],
        command: "git revert 4e8b6c1",
        commandLabel: "Safely reverse a commit",
        commandLabelMy: "Commit ကို လုံခြုံစွာပြန်ဖျက်ရန်",
        tip: "Use revert for commits already shared with others.",
        tipMy: "သူများနဲ့ share ပြီး commit ဆို revert သုံးပါ",
        challenge: "revert",
        check: {
          question: "Best undo for a shared commit?",
          options: ["git revert", "Delete Git", "Remove GitHub"],
          correct: 0,
          success: "Correct. Revert keeps shared history safe.",
        },
        checkMy: {
          question: "Share ပြီး commit ကို ဘယ်လို undo လဲ",
          options: ["git revert", "Git ဖျက်မယ်", "GitHub ဖယ်မယ်"],
          correct: 0,
          success: "မှန်ပါတယ် Revert က shared history ကိုလုံခြုံစေတယ်",
        },
      }),
      lesson({
        id: "stash-reflog",
        title: "Save and find lost work",
        titleMy: "အလုပ်သိမ်းပြီး ပြန်ရှာမယ်",
        summary: "Stash pauses unfinished work. Reflog helps find commits that look lost.",
        summaryMy: "Stash က မပြီးသေးတဲ့အလုပ်ကို ခဏသိမ်းတယ် Reflog က ပျောက်သလိုဖြစ်တဲ့ commit ကိုရှာပေးတယ်",
        points: [
          { title: "Stash", copy: "Pause unfinished edits." },
          { title: "Switch", copy: "Handle another task." },
          { title: "Return", copy: "Apply the saved edits." },
        ],
        pointsMy: [
          { title: "သိမ်းမယ်", copy: "မပြီးသေးတဲ့ edit ခဏသိမ်းပါ" },
          { title: "ပြောင်းမယ်", copy: "တခြား task လုပ်ပါ" },
          { title: "ပြန်ယူ", copy: "သိမ်းထားတဲ့ edit ပြန်ယူပါ" },
        ],
        command: "git reflog",
        commandLabel: "Find recent Git activity",
        commandLabelMy: "မကြာသေးတဲ့ Git activity ရှာရန်",
        tip: "Git rarely loses committed work. Check reflog first.",
        tipMy: "Commit လုပ်ပြီးအလုပ် ပျောက်ခဲတယ် Reflog အရင်ကြည့်ပါ",
        challenge: "reflog",
        check: {
          question: "Where can you find a lost commit?",
          options: ["git reflog", "git color", "git password"],
          correct: 0,
          success: "Correct. Reflog records recent HEAD movements.",
        },
        checkMy: {
          question: "ပျောက်သလိုဖြစ်တဲ့ commit ကို ဘယ်မှာရှာလဲ",
          options: ["git reflog", "git color", "git password"],
          correct: 0,
          success: "မှန်ပါတယ် Reflog က မကြာသေးတဲ့ HEAD အပြောင်းအလဲပြတယ်",
        },
      }),
      lesson({
        id: "solve-git-problems",
        title: "Solve Git problems",
        titleMy: "Git ပြဿနာ ဖြေရှင်းမယ်",
        summary: "Do not guess. Read the error, check the current state, and make one safe change at a time.",
        summaryMy: "မခန့်မှန်းပါနဲ့ Error ကိုဖတ်၊ လက်ရှိအခြေအနေစစ်ပြီး လုံခြုံတဲ့ change တစ်ခုပြီးတစ်ခု လုပ်ပါ",
        points: [
          { title: "Stop", copy: "Do not run random commands." },
          { title: "Inspect", copy: "Read the error and git status." },
          { title: "Fix", copy: "Change one thing, then check again." },
        ],
        pointsMy: [
          { title: "ရပ်မယ်", copy: "Command မသိဘဲ မစမ်းပါနဲ့" },
          { title: "စစ်မယ်", copy: "Error နဲ့ git status ကိုဖတ်ပါ" },
          { title: "ပြင်မယ်", copy: "တစ်ခုပြင်ပြီး ပြန်စစ်ပါ" },
        ],
        command: "git status",
        commandLabel: "Start every Git check here",
        commandLabelMy: "Git ပြဿနာကို ဒီကနေ စစ်ရန်",
        tip: "Copy the exact error message when asking your teammate for help.",
        tipMy: "Teammate ကိုအကူအညီတောင်းရင် error message အတိအကျ copy ပေးပါ",
        challenge: "status",
        check: {
          question: "What is the safest first step after a Git error?",
          options: ["Read it and run status", "Delete the repo", "Force push"],
          correct: 0,
          success: "Correct. Understand the current state before changing it.",
        },
        checkMy: {
          question: "Git error ဖြစ်ရင် အလုံခြုံဆုံး ပထမအဆင့်က ဘာလဲ",
          options: ["Error ဖတ်ပြီး status ကြည့်", "Repo ဖျက်", "Force push"],
          correct: 0,
          success: "မှန်ပါတယ် မပြင်ခင် လက်ရှိအခြေအနေကို နားလည်ပါ",
        },
      }),
    ],
  },
  {
    id: "ssh-device",
    number: "06",
    title: "Connect with SSH",
    description: "Create an SSH key, add it to GitHub, and connect this device securely.",
    duration: "22 min",
    difficulty: "Beginner",
    my: {
      title: "SSH နဲ့ device ချိတ်မယ်",
      description: "SSH key ဖန်တီး၊ GitHub ထည့်ပြီး ဒီ device ကို လုံခြုံစွာ ချိတ်မယ်",
      duration: "၂၂ မိနစ်",
      difficulty: "အစပြုသူ",
    },
    lessons: [
      lesson({
        id: "understand-ssh",
        title: "What SSH does",
        titleMy: "SSH က ဘာလုပ်လဲ",
        summary: "SSH proves that this device is allowed to use your GitHub account without sending your password every time.",
        summaryMy: "SSH က password အကြိမ်တိုင်းမပို့ဘဲ ဒီ device ကို သင့် GitHub account သုံးခွင့်ရှိကြောင်း သက်သေပြတယ်",
        points: [
          { title: "Private key", copy: "Keep it only on your device." },
          { title: "Public key", copy: "Add this part to GitHub." },
          { title: "Secure link", copy: "GitHub checks both parts." },
        ],
        pointsMy: [
          { title: "Private key", copy: "ကိုယ့် device ထဲမှာပဲ သိမ်းပါ" },
          { title: "Public key", copy: "ဒီအပိုင်းကို GitHub ထည့်ပါ" },
          { title: "Secure link", copy: "GitHub က key နှစ်ပိုင်းကို စစ်တယ်" },
        ],
        command: "ssh -V",
        commandLabel: "Check whether SSH is installed",
        commandLabelMy: "SSH install ရှိမရှိ စစ်ရန်",
        tip: "Never share your private key or upload it to a repository.",
        tipMy: "Private key ကို မမျှဝေပါနဲ့ repository ထဲ မတင်ပါနဲ့",
        challenge: "ssh-version",
        check: {
          question: "Which key can you add to GitHub?",
          options: ["Public key", "Private key", "Both keys"],
          correct: 0,
          success: "Correct. Share the public key and protect the private key.",
        },
        checkMy: {
          question: "GitHub ကို ဘယ် key ထည့်နိုင်လဲ",
          options: ["Public key", "Private key", "Key နှစ်ခုလုံး"],
          correct: 0,
          success: "မှန်ပါတယ် Public key ကိုမျှဝေပြီး private key ကိုကာကွယ်ပါ",
        },
      }),
      lesson({
        id: "create-ssh-key",
        title: "Create an SSH key",
        titleMy: "SSH key ဖန်တီးမယ်",
        summary: "Create one key pair for this device. Use your GitHub email as the label.",
        summaryMy: "ဒီ device အတွက် key pair တစ်ခု ဖန်တီးပါ GitHub email ကို label အဖြစ်သုံးပါ",
        points: [
          { title: "Generate", copy: "Create an Ed25519 key." },
          { title: "Protect", copy: "Add a passphrase if possible." },
          { title: "Locate", copy: "Find the new public key file." },
        ],
        pointsMy: [
          { title: "Generate", copy: "Ed25519 key ဖန်တီးပါ" },
          { title: "Protect", copy: "ဖြစ်နိုင်ရင် passphrase ထည့်ပါ" },
          { title: "Locate", copy: "Public key file အသစ်ကိုရှာပါ" },
        ],
        command: 'ssh-keygen -t ed25519 -C "you@example.com"',
        commandLabel: "Generate a key for this device",
        commandLabelMy: "ဒီ device အတွက် key ဖန်တီးရန်",
        tip: "Press Enter to accept the default file location unless you already have a key there.",
        tipMy: "အဲဒီနေရာမှာ key မရှိသေးရင် default file location ကို Enter နှိပ်ပြီးသုံးပါ",
        challenge: "ssh-keygen",
        check: {
          question: "Should two people share one private key?",
          options: ["No", "Yes", "Only on main"],
          correct: 0,
          success: "Correct. Each person and device should have its own key.",
        },
        checkMy: {
          question: "လူနှစ်ယောက် private key တစ်ခု အတူသုံးသင့်လား",
          options: ["မသုံးသင့်", "သုံးသင့်", "Main မှာပဲ"],
          correct: 0,
          success: "မှန်ပါတယ် လူတစ်ယောက်နဲ့ device တစ်ခုစီမှာ ကိုယ်ပိုင် key ရှိသင့်တယ်",
        },
      }),
      lesson({
        id: "add-test-ssh",
        title: "Add and test the key",
        titleMy: "Key ထည့်ပြီး စမ်းမယ်",
        summary: "Copy the public key into GitHub SSH settings, then test the connection from your terminal.",
        summaryMy: "Public key ကို GitHub SSH settings ထဲ copy လုပ်ပြီး terminal ကနေ connection စမ်းပါ",
        points: [
          { title: "Copy", copy: "Copy the .pub file content." },
          { title: "Add", copy: "Paste it into GitHub SSH keys." },
          { title: "Test", copy: "Confirm GitHub recognizes you." },
        ],
        pointsMy: [
          { title: "Copy", copy: ".pub file content ကို copy လုပ်ပါ" },
          { title: "Add", copy: "GitHub SSH keys ထဲ paste လုပ်ပါ" },
          { title: "Test", copy: "GitHub က သင့်ကို သိမသိ စမ်းပါ" },
        ],
        command: "ssh -T git@github.com",
        commandLabel: "Test the GitHub SSH connection",
        commandLabelMy: "GitHub SSH connection စမ်းရန်",
        tip: "The first test may ask you to confirm GitHub's host fingerprint. Read it, then type yes.",
        tipMy: "ပထမ test မှာ GitHub host fingerprint အတည်ပြုခိုင်းနိုင်တယ် ဖတ်ပြီး yes ရိုက်ပါ",
        challenge: "ssh-test",
        check: {
          question: "Which file do you paste into GitHub?",
          options: ["The .pub file", "The private key", "package.json"],
          correct: 0,
          success: "Correct. GitHub receives only the public .pub key.",
        },
        checkMy: {
          question: "GitHub ထဲ ဘယ် file ကို paste လုပ်လဲ",
          options: [".pub file", "Private key", "package.json"],
          correct: 0,
          success: "မှန်ပါတယ် GitHub ကို public .pub key ပဲထည့်ပါ",
        },
      }),
    ],
  },
  {
    id: "issue-contribution",
    number: "07",
    title: "Contribute through issues",
    description: "Find an issue, create a useful report, fork the project, and send a pull request.",
    duration: "32 min",
    difficulty: "Contributor",
    my: {
      title: "Issue ကနေ contribute လုပ်မယ်",
      description: "Issue ရှာ၊ report ရေး၊ project fork လုပ်ပြီး pull request ပို့မယ်",
      duration: "၃၂ မိနစ်",
      difficulty: "Contributor",
    },
    lessons: [
      lesson({
        id: "find-pick-issue",
        title: "Find and pick an issue",
        titleMy: "Issue ရှာပြီး ရွေးမယ်",
        summary: "Read CONTRIBUTING first. Choose a clear, unassigned issue that matches your skill level.",
        summaryMy: "CONTRIBUTING ကို အရင်ဖတ်ပါ ကိုယ့် skill နဲ့ကိုက်ပြီး assign မလုပ်ရသေးတဲ့ issue ကိုရွေးပါ",
        points: [
          { title: "Filter", copy: "Try good first issue or help wanted." },
          { title: "Read", copy: "Understand the expected result." },
          { title: "Ask", copy: "Comment before starting if unclear." },
        ],
        pointsMy: [
          { title: "Filter", copy: "good first issue သို့ help wanted ရှာပါ" },
          { title: "Read", copy: "လိုချင်တဲ့ result ကို နားလည်ပါ" },
          { title: "Ask", copy: "မရှင်းရင် မစခင် comment မေးပါ" },
        ],
        command: "gh issue list --label \"good first issue\"",
        commandLabel: "List beginner-friendly issues",
        commandLabelMy: "အစပြုသူအတွက် issue list ကြည့်ရန်",
        tip: "Do not start an assigned issue without asking the assignee or maintainer.",
        tipMy: "Assign လုပ်ပြီး issue ကို assignee သို့ maintainer မမေးဘဲ မစပါနဲ့",
        challenge: "issue-list",
        check: {
          question: "What should you read before choosing work?",
          options: ["CONTRIBUTING", "Only the title", "Your password"],
          correct: 0,
          success: "Correct. Project contribution rules come first.",
        },
        checkMy: {
          question: "အလုပ်မရွေးခင် ဘာဖတ်သင့်လဲ",
          options: ["CONTRIBUTING", "Title ပဲ", "Password"],
          correct: 0,
          success: "မှန်ပါတယ် Project contribution rules ကို အရင်ဖတ်ပါ",
        },
      }),
      lesson({
        id: "create-clear-issue",
        title: "Create a clear issue",
        titleMy: "ရှင်းတဲ့ issue ဖန်တီးမယ်",
        summary: "Search for duplicates, then write a short title, clear steps, expected result, and actual result.",
        summaryMy: "Issue တူရှိမရှိ အရင်ရှာပါ ပြီးရင် title တိုတို၊ steps၊ expected result နဲ့ actual result ရေးပါ",
        points: [
          { title: "Search", copy: "Check for an existing issue." },
          { title: "Explain", copy: "Give steps to reproduce." },
          { title: "Support", copy: "Add logs or screenshots if useful." },
        ],
        pointsMy: [
          { title: "Search", copy: "Issue ရှိပြီးလား စစ်ပါ" },
          { title: "Explain", copy: "ပြန်ဖြစ်စေမယ့် steps ရေးပါ" },
          { title: "Support", copy: "လိုရင် log သို့ screenshot ထည့်ပါ" },
        ],
        command: "gh issue create",
        commandLabel: "Start a new GitHub issue",
        commandLabelMy: "GitHub issue အသစ် စရန်",
        tip: "One issue should describe one problem or request.",
        tipMy: "Issue တစ်ခုမှာ problem သို့ request တစ်ခုပဲ ရေးပါ",
        challenge: "issue-create",
        check: {
          question: "What makes a bug issue useful?",
          options: ["Clear reproduction steps", "Only 'it broke'", "No details"],
          correct: 0,
          success: "Correct. Clear steps help others see and solve the same problem.",
        },
        checkMy: {
          question: "Bug issue က ဘာရှိရင် အသုံးဝင်လဲ",
          options: ["ရှင်းတဲ့ reproduction steps", "'ပျက်တယ်' ပဲ", "Detail မရှိ"],
          correct: 0,
          success: "မှန်ပါတယ် Clear steps က problem ကို ပြန်တွေ့ပြီး ဖြေရှင်းဖို့ ကူညီတယ်",
        },
      }),
      lesson({
        id: "fork-solve-issue",
        title: "Fork and solve the issue",
        titleMy: "Fork လုပ်ပြီး issue ဖြေရှင်းမယ်",
        summary: "Fork the repository, clone your fork, create one branch for the issue, and make a focused change.",
        summaryMy: "Repository ကို fork၊ ကိုယ့် fork ကို clone၊ issue အတွက် branch တစ်ခုဖန်တီးပြီး focused change လုပ်ပါ",
        points: [
          { title: "Fork", copy: "Create your GitHub copy." },
          { title: "Branch", copy: "Use a name linked to the issue." },
          { title: "Solve", copy: "Change and test only what is needed." },
        ],
        pointsMy: [
          { title: "Fork", copy: "ကိုယ့် GitHub copy ဖန်တီးပါ" },
          { title: "Branch", copy: "Issue နဲ့ဆိုင်တဲ့ name သုံးပါ" },
          { title: "Solve", copy: "လိုအပ်တာပဲ ပြင်ပြီး test လုပ်ပါ" },
        ],
        command: "git switch -c fix/issue-42",
        commandLabel: "Create a branch for the issue",
        commandLabelMy: "Issue အတွက် branch ဖန်တီးရန်",
        tip: "Keep unrelated formatting or cleanup out of the same pull request.",
        tipMy: "မဆိုင်တဲ့ formatting သို့ cleanup ကို pull request တစ်ခုတည်းထဲ မထည့်ပါနဲ့",
        challenge: "branch",
        check: {
          question: "What should one issue branch contain?",
          options: ["One focused fix", "Every unfinished idea", "Other projects"],
          correct: 0,
          success: "Correct. A focused branch is easier to review.",
        },
        checkMy: {
          question: "Issue branch တစ်ခုမှာ ဘာပါသင့်လဲ",
          options: ["Focused fix တစ်ခု", "မပြီးသေးတဲ့ idea အားလုံး", "တခြား projects"],
          correct: 0,
          success: "မှန်ပါတယ် Focused branch က review လုပ်ရလွယ်တယ်",
        },
      }),
      lesson({
        id: "open-issue-pr",
        title: "Open the pull request",
        titleMy: "Pull request ဖွင့်မယ်",
        summary: "Push the branch to your fork, open a pull request, link the issue, and explain how you tested the fix.",
        summaryMy: "Branch ကို ကိုယ့် fork ဆီ push၊ pull request ဖွင့်၊ issue ချိတ်ပြီး fix ကို ဘယ်လို test လုပ်လဲ ရေးပါ",
        points: [
          { title: "Push", copy: "Publish the issue branch." },
          { title: "Link", copy: "Use Closes #issue-number." },
          { title: "Respond", copy: "Update the branch after review." },
        ],
        pointsMy: [
          { title: "Push", copy: "Issue branch ကိုတင်ပါ" },
          { title: "Link", copy: "Closes #issue-number သုံးပါ" },
          { title: "Respond", copy: "Review ပြီး branch ကို update လုပ်ပါ" },
        ],
        command: "gh pr create --fill",
        commandLabel: "Open a pull request from this branch",
        commandLabelMy: "ဒီ branch ကနေ pull request ဖွင့်ရန်",
        tip: "Write Closes #42 in the pull request description to close the issue when merged.",
        tipMy: "Merge ပြီး issue ပိတ်ဖို့ pull request description မှာ Closes #42 ရေးပါ",
        challenge: "pr-create",
        check: {
          question: "How can a pull request link its issue?",
          options: ["Closes #42", "Delete #42", "Branch only"],
          correct: 0,
          success: "Correct. The closing keyword links and closes the issue after merge.",
        },
        checkMy: {
          question: "Pull request က issue ကို ဘယ်လိုချိတ်လဲ",
          options: ["Closes #42", "Delete #42", "Branch ပဲ"],
          correct: 0,
          success: "မှန်ပါတယ် Closing keyword က issue ချိတ်ပြီး merge ပြီးရင်ပိတ်တယ်",
        },
      }),
    ],
  },
];

export const knowledgeTopics = [
  {
    id: "what-is-git",
    category: "Git basics",
    question: "What is Git?",
    answer: "Git is a tool that saves your project history. It shows what changed, who changed it, and when.",
    example: "You can return to yesterday’s working code after a mistake.",
    my: {
      category: "Git အခြေခံ",
      question: "Git ဆိုတာ ဘာလဲ",
      answer: "Git က project history ကို သိမ်းပေးတဲ့ tool ပါ ဘာပြောင်းလဲ၊ ဘယ်သူပြင်၊ ဘယ်အချိန်ပြင်ဆိုတာ ကြည့်နိုင်တယ်",
      example: "အမှားဖြစ်ရင် မနေ့က အလုပ်လုပ်တဲ့ code ကို ပြန်ယူနိုင်တယ်",
    },
  },
  {
    id: "why-use-git",
    category: "Git basics",
    question: "Why do we use Git?",
    answer: "Git keeps work safe, records changes, and lets many people work on one project.",
    example: "You can test a new idea without losing the stable version.",
    my: {
      category: "Git အခြေခံ",
      question: "Git ကို ဘာကြောင့်သုံးလဲ",
      answer: "အလုပ်ကို လုံခြုံစွာသိမ်းဖို့၊ changes မှတ်တမ်းထားဖို့၊ လူအများ project တစ်ခုမှာ အတူလုပ်ဖို့ သုံးတယ်",
      example: "Stable version မပျောက်ဘဲ idea အသစ်ကို စမ်းနိုင်တယ်",
    },
  },
  {
    id: "what-is-repository",
    category: "Git basics",
    question: "What is a repository?",
    answer: "A repository, or repo, is a project folder that Git is tracking. It includes files and their saved history.",
    example: "A website folder becomes a repo after you run git init.",
    my: {
      category: "Git အခြေခံ",
      question: "Repository (repo) ဆိုတာ ဘာလဲ",
      answer: "Repo ဆိုတာ Git က စောင့်ကြည့်မှတ်တမ်းတင်နေတဲ့ project folder ပါ File တွေနဲ့ history ပါဝင်တယ်",
      example: "Website folder မှာ git init run လုပ်ရင် repo ဖြစ်သွားတယ်",
    },
  },
  {
    id: "what-is-commit",
    category: "Git basics",
    question: "What is a commit?",
    answer: "A commit is one saved snapshot of your project. It has an ID, author, time, and message.",
    example: "“Add login button” can be one commit.",
    my: {
      category: "Git အခြေခံ",
      question: "Commit ဆိုတာ ဘာလဲ",
      answer: "Commit ဆိုတာ project ကို တစ်ကြိမ် snapshot သိမ်းထားတာပါ ID၊ author၊ အချိန်နဲ့ message ပါတယ်",
      example: "“Add login button” က commit တစ်ခု ဖြစ်နိုင်တယ်",
    },
  },
  {
    id: "what-is-branch",
    category: "Branches",
    question: "What is a branch?",
    answer: "A branch is a separate line of work. You can change code there without changing main.",
    example: "Build a search feature on feat/search while main stays stable.",
    my: {
      category: "Branch",
      question: "Branch ဆိုတာ ဘာလဲ",
      answer: "Branch ဆိုတာ သီးခြားအလုပ်လမ်းကြောင်းတစ်ခုပါ Main ကို မပြောင်းဘဲ code အသစ်လုပ်နိုင်တယ်",
      example: "Main ကိုတည်ငြိမ်ထားပြီး feat/search မှာ search feature လုပ်နိုင်တယ်",
    },
  },
  {
    id: "why-use-branches",
    category: "Branches",
    question: "Why do we need branches?",
    answer: "Branches keep new or unfinished work away from stable code. They also make review easier.",
    example: "Each task or bug fix gets its own branch.",
    my: {
      category: "Branch",
      question: "Branch ကို ဘာကြောင့်လိုလဲ",
      answer: "အသစ်လုပ်နေတဲ့အလုပ်ကို stable code နဲ့ခွဲထားဖို့ပါ Review လုပ်တာလည်း ပိုလွယ်တယ်",
      example: "Task သို့ bug fix တစ်ခုစီအတွက် branch တစ်ခုသုံးပါ",
    },
  },
  {
    id: "what-is-main",
    category: "Branches",
    question: "What is the main branch?",
    answer: "Main is usually the stable, trusted version of the project. Finished work is merged into it.",
    example: "Do not test risky unfinished work directly on main.",
    my: {
      category: "Branch",
      question: "Main branch ဆိုတာ ဘာလဲ",
      answer: "Main က ပုံမှန်အားဖြင့် project ရဲ့ stable ဖြစ်ပြီး ယုံကြည်ရတဲ့ version ပါ ပြီးသွားတဲ့အလုပ်ကို main ထဲ merge လုပ်တယ်",
      example: "မပြီးသေးတဲ့ risky အလုပ်ကို main မှာ တိုက်ရိုက်မစမ်းပါနဲ့",
    },
  },
  {
    id: "git-vs-github",
    category: "GitHub",
    question: "Are Git and GitHub the same?",
    answer: "No. Git saves history on your computer. GitHub stores Git repositories online and adds team tools.",
    example: "Git works without internet. GitHub needs an internet connection.",
    my: {
      category: "GitHub",
      question: "Git နဲ့ GitHub တူလား",
      answer: "မတူပါ Git က computer မှာ history သိမ်းတယ် GitHub က repo ကို online သိမ်းပြီး team tools ပေးတယ်",
      example: "Git က internet မရှိလည်း အလုပ်လုပ်တယ် GitHub က internet လိုတယ်",
    },
  },
  {
    id: "what-is-remote",
    category: "GitHub",
    question: "What is a remote?",
    answer: "A remote is the online copy connected to your local repository. The common remote name is origin.",
    example: "origin can point to your project on GitHub.",
    my: {
      category: "GitHub",
      question: "Remote ဆိုတာ ဘာလဲ",
      answer: "Remote က local repo နဲ့ချိတ်ထားတဲ့ online copy ပါ အသုံးများတဲ့ remote name က origin ပါ",
      example: "Origin က GitHub ပေါ်က သင့် project ကို ချိတ်ထားနိုင်တယ်",
    },
  },
  {
    id: "clone-vs-fork",
    category: "GitHub",
    question: "What is the difference between clone and fork?",
    answer: "Clone downloads a repository to your computer. Fork creates your own GitHub copy of someone else’s repository.",
    example: "Fork first when you cannot push directly to the original project.",
    my: {
      category: "GitHub",
      question: "Clone နဲ့ fork ဘာကွာလဲ",
      answer: "Clone က repo ကို computer ထဲ download လုပ်တယ် Fork က သူများ repo ကို သင့် GitHub အကောင့်ထဲ copy ဖန်တီးတယ်",
      example: "မူရင်း project ကို push လုပ်ခွင့်မရှိရင် fork အရင်လုပ်ပါ",
    },
  },
  {
    id: "push-vs-pull",
    category: "GitHub",
    question: "What do push and pull mean?",
    answer: "Push sends your commits to GitHub. Pull gets new commits from GitHub.",
    example: "Pull your teammate’s updates, then push your finished work.",
    my: {
      category: "GitHub",
      question: "Push နဲ့ pull ဆိုတာ ဘာလဲ",
      answer: "Push က သင့် commits ကို GitHub တင်တယ် Pull က GitHub က commits အသစ်ကို ယူတယ်",
      example: "Teammate update ကို pull လုပ်ပြီး သင့်အလုပ်ကို push လုပ်ပါ",
    },
  },
  {
    id: "why-collaborate",
    category: "Collaboration",
    question: "Why do developers collaborate?",
    answer: "A team can build more, find mistakes earlier, share knowledge, and maintain a project together.",
    example: "One person builds the page while another reviews it and finds a bug.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Developer တွေ ဘာကြောင့် အတူလုပ်ကြလဲ",
      answer: "အလုပ်ပိုလုပ်နိုင်ဖို့၊ အမှားစောစောရှာဖို့၊ အသိပညာမျှဝေဖို့နဲ့ project ကို အတူထိန်းသိမ်းဖို့ပါ",
      example: "တစ်ယောက်က page လုပ်ပြီး နောက်တစ်ယောက်က review လုပ်ကာ bug ရှာနိုင်တယ်",
    },
  },
  {
    id: "how-to-collaborate",
    category: "Collaboration",
    question: "How do we collaborate with GitHub?",
    answer: "Pull the latest work, create a branch, commit your task, push it, then open a pull request.",
    example: "Pull → branch → edit → commit → push → pull request.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "GitHub နဲ့ ဘယ်လိုအတူလုပ်လဲ",
      answer: "Latest work ကို pull၊ branch ဖန်တီး၊ task commit၊ push၊ ပြီးရင် pull request ဖွင့်ပါ",
      example: "Pull → branch → edit → commit → push → pull request",
    },
  },
  {
    id: "what-is-pull-request",
    category: "Collaboration",
    question: "What is a pull request?",
    answer: "A pull request asks the team to review your branch and merge it into the main project.",
    example: "Explain what changed, why, and how you tested it.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Pull request ဆိုတာ ဘာလဲ",
      answer: "သင့် branch ကို review လုပ်ပြီး main project ထဲ merge ဖို့ team ကို တောင်းတာပါ",
      example: "ဘာပြောင်း၊ ဘာကြောင့်နဲ့ ဘယ်လို test လုပ်ခဲ့တယ်ဆိုတာ ရေးပါ",
    },
  },
  {
    id: "what-is-code-review",
    category: "Collaboration",
    question: "What is code review?",
    answer: "Code review is when teammates read a change before merging it. They check quality, bugs, and clarity.",
    example: "Review the code, ask a question, or suggest a small fix.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Code review ဆိုတာ ဘာလဲ",
      answer: "Merge မလုပ်ခင် teammate တွေက changes ကို ဖတ်ပြီး quality၊ bug နဲ့ ရှင်းလင်းမှု စစ်တာပါ",
      example: "Code ဖတ်၊ မေးခွန်းမေး၊ သို့ fix အသေးစား အကြံပြုပါ",
    },
  },
  {
    id: "what-is-merge",
    category: "Collaboration",
    question: "What does merge mean?",
    answer: "Merge combines changes from one branch into another branch.",
    example: "Merge feat/search into main after review.",
    my: {
      category: "အတူလုပ်ခြင်း",
      question: "Merge ဆိုတာ ဘာလဲ",
      answer: "Branch တစ်ခုက changes ကို နောက် branch တစ်ခုထဲ ပေါင်းထည့်တာပါ",
      example: "Review ပြီးရင် feat/search ကို main ထဲ merge လုပ်ပါ",
    },
  },
  {
    id: "what-is-conflict",
    category: "Problems",
    question: "What is a merge conflict?",
    answer: "A conflict happens when Git cannot choose between two changes. A person must choose the correct result.",
    example: "Two people changed the same line in different ways.",
    my: {
      category: "ပြဿနာဖြေရှင်းခြင်း",
      question: "Merge conflict ဆိုတာ ဘာလဲ",
      answer: "Changes နှစ်ခုထဲက ဘာယူရမလဲ Git မရွေးနိုင်တဲ့အခါ conflict ဖြစ်တယ် လူက မှန်တဲ့ result ကိုရွေးရတယ်",
      example: "လူနှစ်ယောက်က line တစ်ခုတည်းကို ပုံစံမတူ ပြင်ထားတယ်",
    },
  },
  {
    id: "mistake-safety",
    category: "Problems",
    question: "What if I make a mistake?",
    answer: "Stop and run git status. Most Git mistakes can be fixed. Do not run an unknown undo command quickly.",
    example: "Ask a teammate before rewriting shared history.",
    my: {
      category: "ပြဿနာဖြေရှင်းခြင်း",
      question: "အမှားလုပ်မိရင် ဘာလုပ်ရမလဲ",
      answer: "ခဏရပ်ပြီး git status run ပါ Git အမှားအများစု ပြင်လို့ရတယ် မသိတဲ့ undo command ကို အမြန်မလုပ်ပါနဲ့",
      example: "Shared history မပြောင်းခင် teammate ကိုမေးပါ",
    },
  },
  {
    id: "need-internet",
    category: "Common questions",
    question: "Does Git need internet?",
    answer: "No. Local commands like add, commit, branch, and log work offline. GitHub push and pull need internet.",
    example: "You can commit on a plane and push when you are online.",
    my: {
      category: "မေးလေ့ရှိသည်",
      question: "Git သုံးဖို့ internet လိုလား",
      answer: "မလိုပါ Add၊ commit၊ branch နဲ့ log က offline အလုပ်လုပ်တယ် GitHub push နဲ့ pull မှာ internet လိုတယ်",
      example: "Internet မရှိချိန် commit လုပ်ပြီး online ရမှ push လုပ်နိုင်တယ်",
    },
  },
  {
    id: "gitignore-readme",
    category: "Common questions",
    question: "What are README and .gitignore?",
    answer: "README explains the project. .gitignore tells Git which files not to track.",
    example: "Ignore secret .env files and explain setup steps in README.",
    my: {
      category: "မေးလေ့ရှိသည်",
      question: "README နဲ့ .gitignore ဆိုတာ ဘာလဲ",
      answer: "README က project ကိုရှင်းပြတယ် .gitignore က ဘယ် file ကို Git မမှတ်တမ်းတင်ရမလဲ ပြောတယ်",
      example: "Secret .env file ကို ignore လုပ်ပြီး setup အဆင့်ကို README မှာရေးပါ",
    },
  },
  {
    id: "command-options",
    category: "Commands & delivery",
    question: "What does a dash option mean?",
    answer: "Options change how a command works. A short option uses one dash, such as -m. A long option uses two dashes, such as --message.",
    example: "git log --oneline shows each commit on one line.",
    my: {
      category: "Command နှင့် delivery",
      question: "Command မှာ dash option ဆိုတာ ဘာလဲ",
      answer: "Option က command အလုပ်လုပ်ပုံကို ပြောင်းပေးတယ် Short option က -m လို dash တစ်ခု၊ long option က --message လို dash နှစ်ခုသုံးတယ်",
      example: "git log --oneline က commit တစ်ခုကို line တစ်ကြောင်းနဲ့ပြတယ်",
    },
  },
  {
    id: "flag-message",
    category: "Commands & delivery",
    question: "What does -m mean?",
    answer: "-m usually means message. With git commit, it lets you write the commit message in the same command.",
    example: "git commit -m \"Add search\"",
    my: {
      category: "Command နှင့် delivery",
      question: "-m ဆိုတာ ဘာလဲ",
      answer: "-m က ပုံမှန်အားဖြင့် message ကိုဆိုလိုတယ် git commit မှာ commit message ကို command တစ်ကြောင်းတည်းနဲ့ ရေးနိုင်တယ်",
      example: "git commit -m \"Add search\"",
    },
  },
  {
    id: "flag-verbose",
    category: "Commands & delivery",
    question: "What does -v mean?",
    answer: "-v usually means verbose. It asks a command to show more detail. The exact result depends on the command.",
    example: "git remote -v shows remote names and their full URLs.",
    my: {
      category: "Command နှင့် delivery",
      question: "-v ဆိုတာ ဘာလဲ",
      answer: "-v က ပုံမှန်အားဖြင့် verbose၊ အသေးစိတ်ပိုပြတာကို ဆိုလိုတယ် Result က သုံးတဲ့ command ပေါ်မူတည်တယ်",
      example: "git remote -v က remote name နဲ့ URL အပြည့်ပြတယ်",
    },
  },
  {
    id: "what-is-package",
    category: "Commands & delivery",
    question: "What is a package?",
    answer: "A package is reusable code or a bundled application. Projects install packages instead of rebuilding every tool from zero.",
    example: "A React project can install a date-formatting package with npm.",
    my: {
      category: "Command နှင့် delivery",
      question: "Package ဆိုတာ ဘာလဲ",
      answer: "Package ဆိုတာ ပြန်သုံးလို့ရတဲ့ code သို့ စုစည်းထားတဲ့ application ပါ Tool တိုင်းကို အစကမရေးဘဲ package install လုပ်သုံးတယ်",
      example: "React project မှာ date format package ကို npm နဲ့ install လုပ်နိုင်တယ်",
    },
  },
  {
    id: "what-is-release",
    category: "Commands & delivery",
    question: "What is a release?",
    answer: "A release is a named, tested version of the project that is ready for people to use.",
    example: "Version 1.2.0 can be a release with new features and release notes.",
    my: {
      category: "Command နှင့် delivery",
      question: "Release ဆိုတာ ဘာလဲ",
      answer: "Release ဆိုတာ လူတွေသုံးဖို့ အဆင်သင့်ဖြစ်တဲ့ name နဲ့ version ပါတဲ့ စမ်းသပ်ပြီး project version တစ်ခုပါ",
      example: "Feature အသစ်နဲ့ release notes ပါတဲ့ Version 1.2.0 က release တစ်ခုပါ",
    },
  },
  {
    id: "what-is-deploy",
    category: "Commands & delivery",
    question: "What does deploy mean?",
    answer: "Deploy means putting a tested application on a server so users can open and use it.",
    example: "Deploy a website after its build and tests pass.",
    my: {
      category: "Command နှင့် delivery",
      question: "Deploy ဆိုတာ ဘာလဲ",
      answer: "Deploy ဆိုတာ test လုပ်ပြီး application ကို user တွေဖွင့်သုံးနိုင်အောင် server ပေါ်တင်တာပါ",
      example: "Website build နဲ့ test အောင်မြင်ပြီးမှ deploy လုပ်ပါ",
    },
  },
  {
    id: "release-vs-deploy",
    category: "Commands & delivery",
    question: "Are release and deploy the same?",
    answer: "No. A release is a prepared version. A deploy puts a version into an environment where it runs.",
    example: "Create release 1.2.0 today and deploy it to production tomorrow.",
    my: {
      category: "Command နှင့် delivery",
      question: "Release နဲ့ deploy တူလား",
      answer: "မတူပါ Release က အဆင်သင့်ပြင်ထားတဲ့ version ပါ Deploy က အဲဒီ version ကို အလုပ်လုပ်မယ့် environment ပေါ်တင်တာပါ",
      example: "ဒီနေ့ release 1.2.0 ဖန်တီးပြီး မနက်ဖြန် production ကို deploy လုပ်နိုင်တယ်",
    },
  },
  {
    id: "what-is-cicd",
    category: "Commands & delivery",
    question: "What is CI/CD?",
    answer: "CI automatically builds and tests each change. CD automatically prepares or deploys changes after the checks pass.",
    example: "A pull request starts tests. A merge to main can start a deployment.",
    my: {
      category: "Command နှင့် delivery",
      question: "CI/CD ဆိုတာ ဘာလဲ",
      answer: "CI က change တိုင်းကို အလိုအလျောက် build နဲ့ test လုပ်တယ် CD က check အောင်မြင်ရင် release ပြင်ဆင် သို့ deploy လုပ်တယ်",
      example: "Pull request ဖွင့်ရင် test စတယ် Main ကို merge လုပ်ရင် deployment စနိုင်တယ်",
    },
  },
  {
    id: "repository-collaborator",
    category: "People & access",
    question: "What is a repository collaborator?",
    answer: "A collaborator is a person the repository owner directly gives access to. Depending on permission, they may create branches, push code, review, or manage the project.",
    example: "A community team member with write access can push a feature branch to the main repository.",
    my: {
      category: "လူများနှင့် access",
      question: "Repository collaborator ဆိုတာ ဘာလဲ",
      answer: "Collaborator ဆိုတာ repository owner က တိုက်ရိုက် access ပေးထားသူပါ Permission ပေါ်မူတည်ပြီး branch ဖန်တီး၊ push၊ review သို့ project စီမံနိုင်တယ်",
      example: "Write access ရှိတဲ့ community member က main repository ကို feature branch push လုပ်နိုင်တယ်",
    },
  },
  {
    id: "public-contributor",
    category: "People & access",
    question: "What is a public contributor?",
    answer: "A public contributor helps an open-source project without direct write access. They usually fork the repository and send a pull request.",
    example: "Anyone can fix a typo in a public project by forking it and opening a pull request.",
    my: {
      category: "လူများနှင့် access",
      question: "Public contributor ဆိုတာ ဘာလဲ",
      answer: "Public contributor ဆိုတာ direct write access မရှိဘဲ open-source project ကို ကူညီသူပါ ပုံမှန် fork လုပ်ပြီး pull request ပို့တယ်",
      example: "Public project ကို fork လုပ်ပြီး pull request ဖွင့်ကာ typo ပြင်ပေးနိုင်တယ်",
    },
  },
  {
    id: "collaborator-vs-contributor",
    category: "People & access",
    question: "Collaborator and contributor: what is the difference?",
    answer: "A collaborator has direct repository access. A contributor provides accepted work, often through a fork and pull request. A person can be both.",
    example: "A new member may begin as a contributor and later receive collaborator access.",
    my: {
      category: "လူများနှင့် access",
      question: "Collaborator နဲ့ contributor ဘာကွာလဲ",
      answer: "Collaborator က repository ကို direct access ရှိတယ် Contributor က ပုံမှန် fork နဲ့ pull request ကနေ လက်ခံထားတဲ့အလုပ် ပေးသူပါ လူတစ်ယောက်က နှစ်မျိုးလုံးဖြစ်နိုင်တယ်",
      example: "Member အသစ်က contributor အဖြစ်စပြီး နောက်ပိုင်း collaborator access ရနိုင်တယ်",
    },
  },
  {
    id: "repository-permissions",
    category: "People & access",
    question: "What do repository permissions mean?",
    answer: "Read can view and clone. Triage manages issues. Write can push. Maintain manages the repository without sensitive admin actions. Admin controls everything.",
    example: "Give only the lowest permission a person needs for their task.",
    my: {
      category: "လူများနှင့် access",
      question: "Repository permission တွေက ဘာကိုဆိုလိုလဲ",
      answer: "Read က ကြည့်နဲ့ clone လုပ်နိုင်တယ် Triage က issue စီမံတယ် Write က push လုပ်နိုင်တယ် Maintain က sensitive admin action မပါဘဲ repo စီမံတယ် Admin က အားလုံးထိန်းချုပ်တယ်",
      example: "Task အတွက် လိုအပ်တဲ့ အနိမ့်ဆုံး permission ပဲပေးပါ",
    },
  },
  {
    id: "public-contribution-flow",
    category: "People & access",
    question: "How does a public contribution work?",
    answer: "Fork the project, clone your fork, create a branch, commit, push to your fork, and open a pull request to the original project.",
    example: "Fork → clone → branch → commit → push → pull request.",
    my: {
      category: "လူများနှင့် access",
      question: "Public contribution ကို ဘယ်လိုလုပ်လဲ",
      answer: "Project ကို fork၊ fork ကို clone၊ branch ဖန်တီး၊ commit၊ ကိုယ့် fork ကို push၊ ပြီးရင် မူရင်း project ကို pull request ဖွင့်ပါ",
      example: "Fork → clone → branch → commit → push → pull request",
    },
  },
  {
    id: "maintainer-role",
    category: "People & access",
    question: "What does a maintainer do?",
    answer: "A maintainer reviews contributions, protects project quality, plans releases, and decides when changes are ready to merge.",
    example: "A maintainer can request a test before approving a pull request.",
    my: {
      category: "လူများနှင့် access",
      question: "Maintainer က ဘာလုပ်လဲ",
      answer: "Maintainer က contributions review၊ project quality ထိန်း၊ release စီစဉ်ပြီး changes merge လုပ်ဖို့ အဆင်သင့်လား ဆုံးဖြတ်တယ်",
      example: "Pull request approve မလုပ်ခင် test တောင်းနိုင်တယ်",
    },
  },
  {
    id: "short-vs-long-options",
    category: "Command options",
    question: "Are short and long options the same?",
    answer: "Often yes. Short options use one dash and one letter. Long options use two dashes and a full word. Always check the command help because options can differ by command.",
    example: "git commit -m \"Fix menu\" and git commit --message \"Fix menu\" do the same thing.",
    my: {
      category: "Command option များ",
      question: "Short နဲ့ long option တူလား",
      answer: "များသောအားဖြင့် တူတယ် Short option က dash တစ်ခုနဲ့ letter တစ်ခု Long option က dash နှစ်ခုနဲ့ word အပြည့် Command တစ်ခုစီ option မတူနိုင်လို့ help စစ်ပါ",
      example: "git commit -m \"Fix menu\" နဲ့ git commit --message \"Fix menu\" အတူတူပါ",
    },
  },
  {
    id: "help-option",
    category: "Command options",
    question: "What do -h and --help do?",
    answer: "They show command usage and available options. -h is usually shorter. --help may open the full manual.",
    example: "git commit -h shows the options for git commit.",
    my: {
      category: "Command option များ",
      question: "-h နဲ့ --help က ဘာလုပ်လဲ",
      answer: "Command သုံးပုံနဲ့ ရနိုင်တဲ့ options ကိုပြတယ် -h က အကျဉ်းပြတတ်ပြီး --help က manual အပြည့်ဖွင့်နိုင်တယ်",
      example: "git commit -h က git commit options ကိုပြတယ်",
    },
  },
  {
    id: "version-option",
    category: "Command options",
    question: "What does --version do?",
    answer: "--version prints the installed tool version. This is useful when setup instructions require a specific version.",
    example: "git --version",
    my: {
      category: "Command option များ",
      question: "--version က ဘာလုပ်လဲ",
      answer: "Install လုပ်ထားတဲ့ tool version ကိုပြတယ် Setup မှာ version သတ်မှတ်ထားရင် အသုံးဝင်တယ်",
      example: "git --version",
    },
  },
  {
    id: "all-option",
    category: "Command options",
    question: "What do -a and --all mean?",
    answer: "They usually mean all, but the exact action depends on the command. Read the full command before running it.",
    example: "git branch --all lists local and remote branches. git commit -a stages tracked file changes and commits them.",
    my: {
      category: "Command option များ",
      question: "-a နဲ့ --all ဆိုတာ ဘာလဲ",
      answer: "ပုံမှန် all ကိုဆိုလိုပေမယ့် လုပ်ဆောင်ချက်က command ပေါ်မူတည်တယ် မလုပ်ခင် command အပြည့်ကို ဖတ်ပါ",
      example: "git branch --all က local နဲ့ remote branches ပြတယ် git commit -a က tracked file changes ကို stage နဲ့ commit လုပ်တယ်",
    },
  },
  {
    id: "branch-option",
    category: "Command options",
    question: "What do -b and --branch mean?",
    answer: "They usually select or create a branch, depending on the command.",
    example: "git clone --branch develop URL clones the project and checks out develop.",
    my: {
      category: "Command option များ",
      question: "-b နဲ့ --branch ဆိုတာ ဘာလဲ",
      answer: "Command ပေါ်မူတည်ပြီး branch ရွေး သို့ ဖန်တီးတာကို ဆိုလိုတယ်",
      example: "git clone --branch develop URL က project clone လုပ်ပြီး develop ကိုပြောင်းတယ်",
    },
  },
  {
    id: "delete-branch-options",
    category: "Command options",
    question: "What is the difference between -d and -D?",
    answer: "-d safely deletes a merged branch. -D forces deletion even when work is not merged. Use -D only after checking the branch.",
    example: "git branch -d feat/search",
    my: {
      category: "Command option များ",
      question: "-d နဲ့ -D ဘာကွာလဲ",
      answer: "-d က merge ပြီး branch ကို လုံခြုံစွာဖျက်တယ် -D က merge မပြီးလည်း အတင်းဖျက်တယ် Branch စစ်ပြီးမှ -D သုံးပါ",
      example: "git branch -d feat/search",
    },
  },
  {
    id: "force-option",
    category: "Command options",
    question: "What do -f and --force mean?",
    answer: "Force tells Git to skip a safety check. It can overwrite or delete work. Do not use it just because a normal command failed.",
    example: "Ask a teammate before force-pushing a shared branch.",
    my: {
      category: "Command option များ",
      question: "-f နဲ့ --force ဆိုတာ ဘာလဲ",
      answer: "Force က safety check ကိုကျော်ခိုင်းတာပါ အလုပ် overwrite သို့ ဖျက်နိုင်တယ် Normal command fail လို့ ချက်ချင်းမသုံးပါနဲ့",
      example: "Shared branch ကို force push မလုပ်ခင် teammate ကိုမေးပါ",
    },
  },
  {
    id: "upstream-option",
    category: "Command options",
    question: "What do -u and --set-upstream do?",
    answer: "They connect your local branch to a remote branch. After that, plain git push and git pull know which branch to use.",
    example: "git push -u origin feat/search",
    my: {
      category: "Command option များ",
      question: "-u နဲ့ --set-upstream က ဘာလုပ်လဲ",
      answer: "Local branch ကို remote branch နဲ့ချိတ်တယ် ပြီးရင် git push နဲ့ git pull က ဘယ် branch သုံးရမလဲ သိတယ်",
      example: "git push -u origin feat/search",
    },
  },
  {
    id: "amend-option",
    category: "Command options",
    question: "What does --amend do?",
    answer: "--amend replaces the latest commit with an updated commit. Use it for a local commit that has not been shared.",
    example: "git commit --amend -m \"Better message\"",
    my: {
      category: "Command option များ",
      question: "--amend က ဘာလုပ်လဲ",
      answer: "နောက်ဆုံး commit ကို update လုပ်ထားတဲ့ commit နဲ့ အစားထိုးတယ် Share မလုပ်ရသေးတဲ့ local commit အတွက်သုံးပါ",
      example: "git commit --amend -m \"Better message\"",
    },
  },
  {
    id: "staged-cached-options",
    category: "Command options",
    question: "What do --staged and --cached mean?",
    answer: "They refer to changes in the staging area. In many Git commands they mean the same thing.",
    example: "git diff --staged shows what the next commit will contain.",
    my: {
      category: "Command option များ",
      question: "--staged နဲ့ --cached ဆိုတာ ဘာလဲ",
      answer: "Staging area ထဲက changes ကိုဆိုလိုတယ် Git commands အများစုမှာ အတူတူအဓိပ္ပာယ်ရတယ်",
      example: "git diff --staged က နောက် commit ထဲပါမယ့် changes ကိုပြတယ်",
    },
  },
  {
    id: "log-view-options",
    category: "Command options",
    question: "What do --oneline, --graph, and --decorate do?",
    answer: "--oneline shortens each commit. --graph draws branch lines. --decorate shows branch and tag names.",
    example: "git log --oneline --graph --decorate --all",
    my: {
      category: "Command option များ",
      question: "--oneline၊ --graph နဲ့ --decorate က ဘာလုပ်လဲ",
      answer: "--oneline က commit တစ်ခုကို တစ်ကြောင်းပြတယ် --graph က branch lines ဆွဲတယ် --decorate က branch နဲ့ tag names ပြတယ်",
      example: "git log --oneline --graph --decorate --all",
    },
  },
  {
    id: "no-option",
    category: "Command options",
    question: "What does a --no- option mean?",
    answer: "A --no- option turns off a behavior that would otherwise be enabled.",
    example: "git commit --no-verify skips commit hooks. Use it only when you understand why the checks are being skipped.",
    my: {
      category: "Command option များ",
      question: "--no- option ဆိုတာ ဘာလဲ",
      answer: "ပုံမှန်ဖွင့်ထားတဲ့ behavior တစ်ခုကို ပိတ်တာပါ",
      example: "git commit --no-verify က commit hooks ကိုကျော်တယ် Checks ဘာကြောင့်ကျော်လဲ နားလည်မှ သုံးပါ",
    },
  },
];
